import { SyntaxKind } from 'ts-morph'

import type { Logger , PluginConfig } from '../plugins/types.js'

// Build a clean kind-number-to-name map, filtering out range markers (First*, Last*)
// that share enum values with actual node types
export const KIND_MAP: Record<number, string> = {}
for (const [name, value] of Object.entries(SyntaxKind)) {
  if (typeof value !== 'number') continue
  if (name.startsWith('First') || name.startsWith('Last')) continue
  KIND_MAP[value] = name
}

export const silentLogger: Logger = {
  debug() {},
  error() {},
  info() {},
  warn() {},
}

export const defaultConfig: PluginConfig = {
  options: {},
  rules: {},
  transforms: [],
}

export const PROPERTY_MAP: Record<string, string> = {
  alternate: 'alternate',
  arguments: 'arguments',
  block: 'body',
  body: 'body',
  condition: 'test',
  consequent: 'consequent',
  declarationList: 'declarations',
  declarations: 'declarations',
  decorators: 'decorators',
  defaultImport: 'local',
  elements: 'elements',
  elseStatement: 'alternate',
  escapedText: 'name',
  expression: 'argument',
  expressions: 'expressions',
  externalModuleReference: 'source',
  heritageClauses: 'heritage',
  importClause: 'importClause',
  importSpecifier: 'imported',
  initializer: 'init',
  left: 'left',
  members: 'body',
  modifierFlags: 'modifierFlags',
  moduleSpecifier: 'source',
  name: 'name',
  namedBindings: 'namedBindings',
  namedImports: 'namedImports',
  namespaceImport: 'namespaceImport',
  objectLiteral: 'objectValue',
  operand: 'argument',
  operator: 'operator',
  operatorToken: 'operator',
  parameters: 'params',
  properties: 'properties',
  propertyName: 'imported',
  right: 'right',
  statements: 'body',
  stringLiteral: 'importPath',
  test: 'test',
  text: 'raw',
  thenStatement: 'consequent',
  type: 'typeAnnotation',
  typeArguments: 'typeParameters',
  typeParameters: 'typeParameters',
  variableDeclaration: 'param',
}

export const KIND_NAME_ALIASES: Record<string, string> = {
  AnyKeyword: 'TSAnyKeyword',
  ArrayDestructuring: 'ArrayPattern',
  ArrayLiteralExpression: 'ArrayExpression',
  ArrowFunction: 'ArrowFunctionExpression',
  AsExpression: 'TSAsExpression',
  AwaitExpression: 'AwaitExpression',
  BigIntLiteral: 'Literal',
  BinaryExpression: 'BinaryExpression',
  Block: 'BlockStatement',
  BooleanKeyword: 'TSBooleanKeyword',
  BreakStatement: 'BreakStatement',
  CallExpression: 'CallExpression',
  CallSignature: 'TSCallSignatureDeclaration',
  CaseClause: 'SwitchCase',
  CatchClause: 'CatchClause',
  ClassDeclaration: 'ClassDeclaration',
  ClassExpression: 'ClassExpression',
  CommaListExpression: 'SequenceExpression',
  ConditionalExpression: 'ConditionalExpression',
  ConditionalType: 'TSConditionalType',
  ContinueStatement: 'ContinueStatement',
  DebuggerStatement: 'DebuggerStatement',
  AbstractKeyword: 'TSAbstractKeyword',
  AccessorKeyword: 'TSAccessorKeyword',
  AsyncKeyword: 'TSAsyncKeyword',
  ConstKeyword: 'TSConstKeyword',
  DeclareKeyword: 'TSDeclareKeyword',
  OverrideKeyword: 'TSOverrideKeyword',
  PrivateKeyword: 'TSPrivateKeyword',
  ProtectedKeyword: 'TSProtectedKeyword',
  PublicKeyword: 'TSPublicKeyword',
  ReadonlyKeyword: 'TSReadonlyKeyword',
  StaticKeyword: 'TSStaticKeyword',
  DefaultClause: 'SwitchCase',
  DefaultKeyword: 'TSDefaultKeyword',
  DeleteExpression: 'UnaryExpression',
  DoStatement: 'DoWhileStatement',
  ElementAccessExpression: 'MemberExpression',
  EnumDeclaration: 'TSEnumDeclaration',
  ArrayBindingPattern: 'ArrayPattern',
  ObjectBindingPattern: 'ObjectPattern',
  ExportDeclaration: 'ExportNamedDeclaration',
  ExportAssignment: 'ExportDefaultDeclaration',
  ExportKeyword: 'TSExportKeyword',
  ExportSpecifier: 'ExportSpecifier',
  ExpressionStatement: 'ExpressionStatement',
  ExternalModuleReference: 'TSExternalModuleReference',
  FalseKeyword: 'BooleanLiteral',
  ForInStatement: 'ForInStatement',
  ForOfStatement: 'ForOfStatement',
  ForStatement: 'ForStatement',
  FunctionDeclaration: 'FunctionDeclaration',
  FunctionExpression: 'FunctionExpression',
  GetAccessor: 'MethodDefinition',
  Identifier: 'Identifier',
  IfStatement: 'IfStatement',
  ImportDeclaration: 'ImportDeclaration',
  ImportEqualsDeclaration: 'TSImportEqualsDeclaration',
  ImportExpression: 'Import',
  ImportSpecifier: 'ImportSpecifier',
  InExpression: 'BinaryExpression',
  InstanceOfExpression: 'BinaryExpression',
  InterfaceDeclaration: 'TSInterfaceDeclaration',
  JsxAttribute: 'JSXAttribute',
  JsxClosingElement: 'JSXClosingElement',
  JsxClosingFragment: 'JSXClosingFragment',
  JsxElement: 'JSXElement',
  JsxExpression: 'JSXExpressionContainer',
  JsxFragment: 'JSXFragment',
  JsxOpeningElement: 'JSXOpeningElement',
  JsxOpeningFragment: 'JSXOpeningFragment',
  JsxSelfClosingElement: 'JSXSelfClosingElement',
  JsxSpreadAttribute: 'JSXSpreadAttribute',
  JsxText: 'JSXText',
  LabeledStatement: 'LabeledStatement',
  LiteralType: 'TSLiteralType',
  MethodDeclaration: 'MethodDefinition',
  ModuleDeclaration: 'TSModuleDeclaration',
  NamedTupleMember: 'TSNamedTupleMember',
  NewExpression: 'NewExpression',
  NonNullExpression: 'TSNonNullExpression',
  NoSubstitutionTemplateLiteral: 'TemplateLiteral',
  NullKeyword: 'Literal',
  NumberKeyword: 'TSNumberKeyword',
  NumericLiteral: 'Literal',
  ObjectDestructuring: 'ObjectPattern',
  ObjectKeyword: 'TSObjectKeyword',
  ObjectLiteralExpression: 'ObjectExpression',
  PostfixUnaryExpression: 'UpdateExpression',
  PrefixUnaryExpression: 'UnaryExpression',
  PrivateIdentifier: 'PrivateIdentifier',
  PropertyAccessExpression: 'MemberExpression',
  PropertyAssignment: 'Property',
  PropertyDeclaration: 'PropertyDefinition',
  RegularExpressionLiteral: 'RegExpLiteral',
  ReturnStatement: 'ReturnStatement',
  SatisfiesExpression: 'TSSatisfiesExpression',
  SetAccessor: 'MethodDefinition',
  ShorthandPropertyAssignment: 'Property',
  SpreadAssignment: 'SpreadElement',
  SpreadElement: 'SpreadElement',
  StaticBlock: 'StaticBlock',
  StringKeyword: 'TSStringKeyword',
  StringLiteral: 'Literal',
  SuperKeyword: 'Super',
  SwitchStatement: 'SwitchStatement',
  TaggedTemplateExpression: 'TaggedTemplateExpression',
  TemplateExpression: 'TemplateLiteral',
  ThisKeyword: 'ThisExpression',
  ThrowStatement: 'ThrowStatement',
  TrueKeyword: 'BooleanLiteral',
  TryStatement: 'TryStatement',
  ArrayType: 'TSArrayType',
  ConstructorType: 'TSConstructorType',
  Constructor: 'MethodDefinition',
  ExpressionWithTypeArguments: 'TSExpressionWithTypeArguments',
  FunctionType: 'TSFunctionType',
  HeritageClause: 'TSHeritageClause',
  IndexSignature: 'TSIndexSignature',
  IndexedAccessType: 'TSIndexedAccessType',
  InferType: 'TSInferType',
  IntersectionType: 'TSIntersectionType',
  MappedType: 'TSMappedType',
  MethodSignature: 'TSMethodSignature',
  OptionalType: 'TSOptionalType',
  ParenthesizedType: 'TSParenthesizedType',
  PropertySignature: 'TSPropertySignature',
  QualifiedName: 'TSQualifiedName',
  RestType: 'TSRestType',
  TupleType: 'TSTupleType',
  TypeOperator: 'TSTypeOperator',
  TypeParameter: 'TSTypeParameter',
  TypePredicate: 'TSTypePredicate',
  TypeQuery: 'TSTypeQuery',
  UnionType: 'TSUnionType',
  EnumMember: 'TSEnumMember',
  TSArrayType: 'TSArrayType',
  TSEnumMember: 'TSEnumMember',
  TSInterfaceBody: 'TSInterfaceBody',
  TSInterfaceDeclaration: 'TSInterfaceDeclaration',
  TSUnionType: 'TSUnionType',
  TypeAliasDeclaration: 'TSTypeAliasDeclaration',
  TypeAnnotation: 'TSTypeAnnotation',
  TypeAssertion: 'TSTypeAssertion',
  TypeLiteral: 'TSTypeLiteral',
  TypeOfExpression: 'UnaryExpression',
  TypeReference: 'TSTypeReference',
  UnknownKeyword: 'TSUnknownKeyword',
  VariableDeclaration: 'VariableDeclarator',
  VariableDeclarationList: 'VariableDeclaration',
  VariableStatement: 'VariableDeclaration',
  VoidExpression: 'UnaryExpression',
  VoidKeyword: 'TSVoidKeyword',
  WhileStatement: 'WhileStatement',
  YieldExpression: 'YieldExpression',
}

export const KIND_SPECIFIC_MAP: Record<string, Record<string, string>> = {
  ArrowFunction: { type: 'returnType' },
  AwaitExpression: { expression: 'argument' },
  CallExpression: { expression: 'callee' },
  CallSignature: { type: 'returnType' },
  CaseClause: { expression: 'test', statements: 'consequent' },
  CatchClause: { block: 'body', variableDeclaration: 'param' },
  ClassDeclaration: { name: 'id' },
  ClassExpression: { name: 'id' },
  ConditionalExpression: { condition: 'test', whenFalse: 'alternate', whenTrue: 'consequent' },
  ConstructSignature: { type: 'returnType' },
  ObjectBindingPattern: { elements: 'properties' },
  DefaultClause: { statements: 'consequent' },
  DeleteExpression: { expression: 'argument' },
  DoStatement: { expression: 'test', statement: 'body' },
  ElementAccessExpression: { argumentExpression: 'property', expression: 'object' },
  EnumDeclaration: { members: 'members', name: 'id' },
  EnumMember: { name: 'id' },
  ExportSpecifier: { name: 'exported', propertyName: 'imported' },
  ExportAssignment: { expression: 'declaration' },
  ExpressionStatement: { expression: 'expression' },
  AsExpression: { expression: 'expression' },
  NonNullExpression: { expression: 'expression' },
  SatisfiesExpression: { expression: 'expression' },
  TypeAssertion: { expression: 'expression' },
  ForInStatement: { expression: 'right', initializer: 'left', statement: 'body' },
  ForOfStatement: { expression: 'right', initializer: 'left', statement: 'body' },
  ForStatement: {
    condition: 'test',
    incrementor: 'update',
    initializer: 'init',
    statement: 'body',
  },
  FunctionDeclaration: { name: 'id', type: 'returnType' },
  FunctionExpression: { type: 'returnType' },
  GetAccessor: { name: 'key', type: 'returnType' },
  IfStatement: { elseStatement: 'alternate', expression: 'test', thenStatement: 'consequent' },
  InterfaceDeclaration: { name: 'id' },
  ImportSpecifier: { name: 'local', propertyName: 'imported' },
  LabeledStatement: { statement: 'body' },
  MethodDeclaration: { name: 'key', type: 'returnType' },
  MethodSignature: { name: 'key', type: 'returnType' },
  ModuleDeclaration: { name: 'id' },
  NewExpression: { expression: 'callee' },
  ObjectLiteralExpression: { members: 'properties' },
  ParenthesizedExpression: { expression: 'expression' },
  PostfixUnaryExpression: { operand: 'argument' },
  PrefixUnaryExpression: { operand: 'argument' },
  PropertyAccessExpression: { expression: 'object', name: 'property' },
  PropertyAssignment: { initializer: 'value', name: 'key' },
  PropertyDeclaration: { initializer: 'value', name: 'key', type: 'typeAnnotation' },
  PropertySignature: { name: 'key', type: 'typeAnnotation' },
  ShorthandPropertyAssignment: { name: 'key' },
  ReturnStatement: { expression: 'argument' },
  SetAccessor: { name: 'key' },
  SpreadAssignment: { expression: 'argument' },
  SpreadElement: { expression: 'argument' },
  SwitchStatement: { caseBlock: 'cases', expression: 'discriminant' },
  TaggedTemplateExpression: { template: 'quasi' },
  ThrowStatement: { expression: 'argument' },
  TryStatement: { catchClause: 'handler', finallyBlock: 'finalizer', tryBlock: 'block' },
  TypeAliasDeclaration: { name: 'id', type: 'typeAnnotation' },
  TypeOfExpression: { expression: 'argument' },
  VariableDeclaration: { name: 'id', type: 'typeAnnotation' },
  VoidExpression: { expression: 'argument' },
  WhileStatement: { expression: 'test', statement: 'body' },
  WithStatement: { statement: 'body' },
  YieldExpression: { expression: 'argument' },
}

export const MAX_DEPTH = 5

export const SKIP_KEYS = new Set([
  'colonToken',
  'emitNode',
  'end',
  'endFlowNode',
  'equalsGreaterThanToken',
  'exclamationToken',
  'flags',
  'flowNode',
  'heritage',
  'id',
  'jlChildren',
  'jsDoc',
  'kind',
  'locals',
  'localSymbol',
  'modifierFlagsCache',
  'multiLine',
  'nextContainer',
  'numericLiteralFlags',
  'original',
  'parent',
  'pos',
  'questionDotToken',
  'questionToken',
  'rawText',
  'returnFlowNode',
  'symbol',
  'templateFlags',
  'transformFlags',
])

export const MODIFIER_MAP: Record<string, string> = {
  AbstractKeyword: 'abstract',
  AsyncKeyword: 'async',
  ConstKeyword: 'const',
  DeclareKeyword: 'declare',
  DefaultKeyword: 'default',
  ExportKeyword: 'export',
  ReadonlyKeyword: 'readonly',
  StaticKeyword: 'static',
}

export const ACCESSIBILITY_MAP: Record<string, string> = {
  PrivateKeyword: 'private',
  ProtectedKeyword: 'protected',
  PublicKeyword: 'public',
}

export const OPERATOR_TOKEN_MAP: Record<string, string> = {
  AmpersandAmpersandEqualsToken: '&&=',
  AmpersandAmpersandToken: '&&',
  AmpersandEqualsToken: '&=',
  AmpersandToken: '&',
  ArrowToken: '=>',
  AsteriskAsteriskEqualsToken: '**=',
  AsteriskAsteriskToken: '**',
  AsteriskEqualsToken: '*=',
  AsteriskToken: '*',
  BarBarEqualsToken: '||=',
  BarBarToken: '||',
  BarEqualsToken: '|=',
  BarToken: '|',
  CaretEqualsToken: '^=',
  CaretToken: '^',
  ColonToken: ':',
  CommaToken: ',',
  DotDotDotToken: '...',
  DotToken: '.',
  EqualsEqualsEqualsToken: '===',
  EqualsEqualsToken: '==',
  EqualsToken: '=',
  ExclamationEqualsEqualsToken: '!==',
  ExclamationEqualsToken: '!=',
  ExclamationToken: '!',
  GreaterThanEqualsToken: '>=',
  GreaterThanGreaterThanEqualsToken: '>>=',
  GreaterThanGreaterThanGreaterThanEqualsToken: '>>>=',
  GreaterThanGreaterThanGreaterThanToken: '>>>',
  GreaterThanGreaterThanToken: '>>',
  GreaterThanToken: '>',
  InKeyword: 'in',
  InstanceOfKeyword: 'instanceof',
  LessThanEqualsToken: '<=',
  LessThanLessThanEqualsToken: '<<=',
  LessThanLessThanToken: '<<',
  LessThanToken: '<',
  MinusEqualsToken: '-=',
  MinusMinusToken: '--',
  MinusToken: '-',
  OfKeyword: 'of',
  PercentEqualsToken: '%=',
  PercentToken: '%',
  PlusEqualsToken: '+=',
  PlusPlusToken: '++',
  PlusToken: '+',
  QuestionDotToken: '?.',
  QuestionQuestionEqualsToken: '??=',
  QuestionQuestionToken: '??',
  SemicolonToken: ';',
  SlashEqualsToken: '/=',
  SlashToken: '/',
  TildeToken: '~',
}

export const ASSIGNMENT_OPERATORS = new Set([
  '%=',
  '&&=',
  '&=',
  '**=',
  '*=',
  '+=',
  '-=',
  '/=',
  '<<=',
  '=',
  '>>=',
  '>>>=',
  '??=',
  '^=',
  '|=',
  '||=',
])

export const LOGICAL_OPERATORS = new Set(['&&', '??', '||'])

export const EXPORTABLE_KINDS = new Set([
  'ClassDeclaration',
  'EnumDeclaration',
  'FunctionDeclaration',
  'InterfaceDeclaration',
  'ModuleDeclaration',
  'TypeAliasDeclaration',
])
