import { SyntaxKind } from 'ts-morph'
import type { Logger } from '../plugins/types.js'
import type { PluginConfig } from '../plugins/types.js'

// Build a clean kind-number-to-name map, filtering out range markers (First*, Last*)
// that share enum values with actual node types
export const KIND_MAP: Record<number, string> = {}
for (const [name, value] of Object.entries(SyntaxKind)) {
  if (typeof value !== 'number') continue
  if (name.startsWith('First') || name.startsWith('Last')) continue
  KIND_MAP[value] = name
}

export const silentLogger: Logger = {
  debug: () => {},
  info: () => {},
  warn: () => {},
  error: () => {},
}

export const defaultConfig: PluginConfig = {
  options: {},
  rules: {},
  transforms: [],
}

export const PROPERTY_MAP: Record<string, string> = {
  block: 'body',
  expression: 'argument',
  expressions: 'expressions',
  escapedText: 'name',
  text: 'raw',
  initializer: 'init',
  left: 'left',
  right: 'right',
  test: 'test',
  consequent: 'consequent',
  alternate: 'alternate',
  operatorToken: 'operator',
  condition: 'test',
  body: 'body',
  thenStatement: 'consequent',
  elseStatement: 'alternate',
  declarationList: 'declarations',
  declarations: 'declarations',
  name: 'name',
  type: 'typeAnnotation',
  typeArguments: 'typeParameters',
  typeParameters: 'typeParameters',
  parameters: 'params',
  arguments: 'arguments',
  heritageClauses: 'heritage',
  members: 'body',
  elements: 'elements',
  properties: 'properties',
  objectLiteral: 'objectValue',
  importClause: 'importClause',
  moduleSpecifier: 'source',
  namedImports: 'namedImports',
  namespaceImport: 'namespaceImport',
  stringLiteral: 'importPath',
  defaultImport: 'local',
  namedBindings: 'namedBindings',
  importSpecifier: 'imported',
  propertyName: 'imported',
  externalModuleReference: 'source',
  decorators: 'decorators',
  modifierFlags: 'modifierFlags',
  statements: 'body',
  variableDeclaration: 'param',
  operand: 'argument',
  operator: 'operator',
}

export const KIND_NAME_ALIASES: Record<string, string> = {
  Block: 'BlockStatement',
  StringLiteral: 'Literal',
  NumericLiteral: 'Literal',
  BigIntLiteral: 'Literal',
  TrueKeyword: 'BooleanLiteral',
  FalseKeyword: 'BooleanLiteral',
  NullKeyword: 'Literal',
  RegularExpressionLiteral: 'RegExpLiteral',
  ObjectLiteralExpression: 'ObjectExpression',
  ArrayLiteralExpression: 'ArrayExpression',
  FunctionExpression: 'FunctionExpression',
  ArrowFunction: 'ArrowFunctionExpression',
  PropertyAccessExpression: 'MemberExpression',
  ElementAccessExpression: 'MemberExpression',
  CallExpression: 'CallExpression',
  NewExpression: 'NewExpression',
  BinaryExpression: 'BinaryExpression',
  PrefixUnaryExpression: 'UnaryExpression',
  PostfixUnaryExpression: 'UpdateExpression',
  ConditionalExpression: 'ConditionalExpression',
  VariableDeclaration: 'VariableDeclarator',
  VariableDeclarationList: 'VariableDeclaration',
  VariableStatement: 'VariableDeclaration',
  FunctionDeclaration: 'FunctionDeclaration',
  ClassDeclaration: 'ClassDeclaration',
  InterfaceDeclaration: 'TSInterfaceDeclaration',
  ImportDeclaration: 'ImportDeclaration',
  ImportEqualsDeclaration: 'TSImportEqualsDeclaration',
  ImportExpression: 'Import',
  ExportDeclaration: 'ExportDeclaration',
  ReturnStatement: 'ReturnStatement',
  ThrowStatement: 'ThrowStatement',
  IfStatement: 'IfStatement',
  ForStatement: 'ForStatement',
  ForInStatement: 'ForInStatement',
  ForOfStatement: 'ForOfStatement',
  WhileStatement: 'WhileStatement',
  DoStatement: 'DoWhileStatement',
  SwitchStatement: 'SwitchStatement',
  TryStatement: 'TryStatement',
  ExpressionStatement: 'ExpressionStatement',
  TypeReference: 'TSTypeReference',
  TypeLiteral: 'TSTypeLiteral',
  EnumDeclaration: 'TSEnumDeclaration',
  ModuleDeclaration: 'TSModuleDeclaration',
  ImportSpecifier: 'ImportSpecifier',
  ExportSpecifier: 'ExportSpecifier',
  CatchClause: 'CatchClause',
  CaseClause: 'SwitchCase',
  DefaultClause: 'SwitchCase',
  PropertyDeclaration: 'PropertyDefinition',
  PropertyAssignment: 'Property',
  MethodDeclaration: 'MethodDefinition',
  Constructor: 'MethodDefinition',
  GetAccessor: 'MethodDefinition',
  SetAccessor: 'MethodDefinition',
  ShorthandPropertyAssignment: 'Property',
  SpreadAssignment: 'SpreadElement',
  SpreadElement: 'SpreadElement',
  TemplateExpression: 'TemplateLiteral',
  NoSubstitutionTemplateLiteral: 'TemplateLiteral',
  TaggedTemplateExpression: 'TaggedTemplateExpression',
  AwaitExpression: 'AwaitExpression',
  YieldExpression: 'YieldExpression',
  DeleteExpression: 'UnaryExpression',
  VoidExpression: 'UnaryExpression',
  TypeOfExpression: 'UnaryExpression',
  InstanceOfExpression: 'BinaryExpression',
  InExpression: 'BinaryExpression',
  AsExpression: 'TSAsExpression',
  TypeAssertion: 'TSTypeAssertion',
  NonNullExpression: 'TSNonNullExpression',
  ParenthesizedExpression: 'SequenceExpression',
  ObjectDestructuring: 'ObjectPattern',
  ArrayDestructuring: 'ArrayPattern',
  ComputedPropertyName: 'Literal',
  DefaultKeyword: 'Literal',
  SuperKeyword: 'Super',
  ThisKeyword: 'ThisExpression',
  BreakStatement: 'BreakStatement',
  ContinueStatement: 'ContinueStatement',
  DebuggerStatement: 'DebuggerStatement',
  LabeledStatement: 'LabeledStatement',
  ClassExpression: 'ClassExpression',
  Identifier: 'Identifier',
  PrivateIdentifier: 'PrivateIdentifier',
  TSAnyKeyword: 'TSAnyKeyword',
  TSArrayType: 'TSArrayType',
  TSUnionType: 'TSUnionType',
  TSEnumMember: 'TSEnumMember',
  TSInterfaceDeclaration: 'TSInterfaceDeclaration',
  TSInterfaceBody: 'TSInterfaceBody',
  StaticBlock: 'StaticBlock',
  AnyKeyword: 'TSAnyKeyword',
  BooleanKeyword: 'TSBooleanKeyword',
  NumberKeyword: 'TSNumberKeyword',
  StringKeyword: 'TSStringKeyword',
  VoidKeyword: 'TSVoidKeyword',
  UnknownKeyword: 'TSUnknownKeyword',
  ObjectKeyword: 'TSObjectKeyword',
  CallSignature: 'TSCallSignatureDeclaration',
  TypeAliasDeclaration: 'TSTypeAliasDeclaration',
  ExternalModuleReference: 'TSExternalModuleReference',
  ExportKeyword: 'TSExportKeyword',
  TypeAnnotation: 'TSTypeAnnotation',
}

export const KIND_SPECIFIC_MAP: Record<string, Record<string, string>> = {
  SwitchStatement: { expression: 'discriminant', caseBlock: 'cases' },
  CaseClause: { expression: 'test', statements: 'consequent' },
  DefaultClause: { statements: 'consequent' },
  TryStatement: { tryBlock: 'block', catchClause: 'handler', finallyBlock: 'finalizer' },
  IfStatement: { expression: 'test', thenStatement: 'consequent', elseStatement: 'alternate' },
  ForStatement: {
    initializer: 'init',
    condition: 'test',
    incrementor: 'update',
    statement: 'body',
  },
  ForInStatement: { expression: 'right', initializer: 'left', statement: 'body' },
  ForOfStatement: { expression: 'right', initializer: 'left', statement: 'body' },
  LabeledStatement: { statement: 'body' },
  WithStatement: { statement: 'body' },
  DoStatement: { expression: 'test', statement: 'body' },
  WhileStatement: { expression: 'test', statement: 'body' },
  CallExpression: { expression: 'callee' },
  NewExpression: { expression: 'callee' },
  PropertyAccessExpression: { expression: 'object', name: 'property' },
  ElementAccessExpression: { expression: 'object', argumentExpression: 'property' },
  ThrowStatement: { expression: 'argument' },
  ReturnStatement: { expression: 'argument' },
  DeleteExpression: { expression: 'argument' },
  VoidExpression: { expression: 'argument' },
  TypeOfExpression: { expression: 'argument' },
  AwaitExpression: { expression: 'argument' },
  YieldExpression: { expression: 'argument' },
  PrefixUnaryExpression: { operand: 'argument' },
  PostfixUnaryExpression: { operand: 'argument' },
  VariableDeclaration: { name: 'id', type: 'typeAnnotation' },
  FunctionDeclaration: { name: 'id', type: 'returnType' },
  FunctionExpression: { type: 'returnType' },
  ArrowFunction: { type: 'returnType' },
  ClassDeclaration: { name: 'id' },
  PropertyDeclaration: { name: 'key', initializer: 'value' },
  PropertyAssignment: { name: 'key', initializer: 'value' },
  MethodDeclaration: { name: 'key' },
  GetAccessor: { name: 'key' },
  SetAccessor: { name: 'key' },
  ImportSpecifier: { name: 'local', propertyName: 'imported' },
  ExportSpecifier: { name: 'exported', propertyName: 'imported' },
  ParenthesizedExpression: { expression: 'expression' },
  SpreadElement: { expression: 'argument' },
  SpreadAssignment: { expression: 'argument' },
  TaggedTemplateExpression: { template: 'quasi' },
}

export const MAX_DEPTH = 5

export const SKIP_KEYS = new Set([
  'kind',
  'pos',
  'end',
  'flags',
  'modifierFlagsCache',
  'transformFlags',
  'parent',
  'original',
  'jlChildren',
  'symbol',
  'locals',
  'nextContainer',
  'id',
])

export const OPERATOR_TOKEN_MAP: Record<string, string> = {
  EqualsEqualsToken: '==',
  EqualsEqualsEqualsToken: '===',
  ExclamationEqualsToken: '!=',
  ExclamationEqualsEqualsToken: '!==',
  LessThanToken: '<',
  LessThanEqualsToken: '<=',
  GreaterThanToken: '>',
  GreaterThanEqualsToken: '>=',
  PlusToken: '+',
  MinusToken: '-',
  AsteriskToken: '*',
  SlashToken: '/',
  PercentToken: '%',
  AsteriskAsteriskToken: '**',
  AmpersandToken: '&',
  BarToken: '|',
  CaretToken: '^',
  LessThanLessThanToken: '<<',
  GreaterThanGreaterThanToken: '>>',
  GreaterThanGreaterThanGreaterThanToken: '>>>',
  EqualsToken: '=',
  PlusEqualsToken: '+=',
  MinusEqualsToken: '-=',
  AsteriskEqualsToken: '*=',
  SlashEqualsToken: '/=',
  PercentEqualsToken: '%=',
  AsteriskAsteriskEqualsToken: '**=',
  AmpersandEqualsToken: '&=',
  BarEqualsToken: '|=',
  CaretEqualsToken: '^=',
  LessThanLessThanEqualsToken: '<<=',
  GreaterThanGreaterThanEqualsToken: '>>=',
  GreaterThanGreaterThanGreaterThanEqualsToken: '>>>=',
  AmpersandAmpersandToken: '&&',
  BarBarToken: '||',
  QuestionQuestionToken: '??',
  AmpersandAmpersandEqualsToken: '&&=',
  BarBarEqualsToken: '||=',
  QuestionQuestionEqualsToken: '??=',
  DotDotDotToken: '...',
  CommaToken: ',',
  ColonToken: ':',
  SemicolonToken: ';',
  ArrowToken: '=>',
  DotToken: '.',
  QuestionDotToken: '?.',
  ExclamationToken: '!',
  TildeToken: '~',
  InKeyword: 'in',
  InstanceOfKeyword: 'instanceof',
  OfKeyword: 'of',
}

export const ASSIGNMENT_OPERATORS = new Set([
  '=',
  '+=',
  '-=',
  '*=',
  '/=',
  '%=',
  '**=',
  '&=',
  '|=',
  '^=',
  '<<=',
  '>>=',
  '>>>=',
  '&&=',
  '||=',
  '??=',
])

export const LOGICAL_OPERATORS = new Set(['&&', '||', '??'])

export const EXPORTABLE_KINDS = new Set([
  'FunctionDeclaration',
  'ClassDeclaration',
  'InterfaceDeclaration',
  'EnumDeclaration',
  'TypeAliasDeclaration',
  'ModuleDeclaration',
])
