# These are supported funding platforms

github: # Replace with up to 5 GitHub Sponsors-enabled usernames
  - your_username
  - another_username

patreon: # Replace with a single Patreon username
  - your_patreon_username

open_collective: # Replace with your Open Collective username
  - your_open_collective_username

ko_fi: # Replace with your Ko-fi username
  - your_ko_fi_username
