import chalk from 'chalk'

export interface DangerfileOptions {
  ciCommand: string
  outputFile: string
  resultsFile: string
}

export const DEFAULT_CI_COMMAND = 'codeforge analyze --format json --output codeforge-results.json'
export const DEFAULT_OUTPUT_FILE = 'dangerfile.js'
export const DEFAULT_RESULTS_FILE = 'codeforge-results.json'

function extractResultsFile(ciCommand: string): string {
  const match = ciCommand.match(/--output\s+(\S+)/)
  return match?.[1] ?? DEFAULT_RESULTS_FILE
}

export function generateDangerfileContent(options: DangerfileOptions): string {
  const resultsFile = extractResultsFile(options.ciCommand)
  return `// CodeForge Dangerfile Integration
// This file was auto-generated by \`codeforge danger\`
// Customize as needed for your project

const { execSync } = require("child_process");
const fs = require("fs");

// Run CodeForge analysis
execSync("${options.ciCommand}", { stdio: "inherit" });

// Read results
const results = JSON.parse(fs.readFileSync("${resultsFile}", "utf8"));

// Report violations
for (const file of results.files) {
  if (file.violations.length === 0) continue;

  for (const violation of file.violations) {
    const location = \`\${violation.filePath}#L\${violation.line}\`;
    const message = \`[\${violation.ruleId}] \${violation.message} (\${location})\`;

    if (violation.severity === "error") {
      fail(message);
    } else if (violation.severity === "warning") {
      warn(message);
    } else {
      message(message);
    }
  }
}

const { summary } = results;
if (summary.errorCount > 0) {
  fail(\`CodeForge found \${summary.errorCount} errors across \${summary.filesWithViolations} files.\`);
}
if (summary.warningCount > 0) {
  warn(\`CodeForge found \${summary.warningCount} warnings.\`);
}
`
}

export function resolveDangerOptions(flags: Record<string, unknown>): DangerfileOptions {
  const ciCommand = ((flags['ci-command'] ?? flags.ciCommand) as string) ?? DEFAULT_CI_COMMAND
  return {
    ciCommand,
    outputFile: (flags.output as string) ?? DEFAULT_OUTPUT_FILE,
    resultsFile: extractResultsFile(ciCommand),
  }
}

export function validateDangerOutputPath(outputPath: string): { valid: boolean; error?: string } {
  if (!outputPath || outputPath.trim().length === 0) {
    return { error: 'Output path cannot be empty.', valid: false }
  }

  const basename = outputPath.split('/').pop() ?? ''
  if (!basename.endsWith('.js') && !basename.endsWith('.ts')) {
    return { error: `Output file must be a .js or .ts file: ${outputPath}`, valid: false }
  }

  return { valid: true }
}

export function displayDangerNextSteps(logFn: (msg: string) => void): void {
  logFn('')
  logFn(chalk.bold('Next steps:'))
  logFn(chalk.gray('  1. Install Danger.js: npm install danger --save-dev'))
  logFn(chalk.gray('  2. Review the generated Dangerfile and customize as needed'))
  logFn(chalk.gray('  3. Run danger ci in your CI pipeline to post PR comments'))
  logFn(chalk.gray('  4. Ensure codeforge is installed in your CI environment'))
}
