export const bestPracticesMap: Record<string, string[]> = {
  'consistent-imports': [
    'Use a single import style (named, default, or namespace) consistently',
    'Configure your import style in project-wide linting rules',
    'Avoid mixing import styles for the same module',
    'Use auto-fix tools to normalize import statements across the codebase',
  ],
  'consistent-type-exports': [
    'Use export type for type-only exports to clarify intent',
    'Keep runtime and type-only exports visually distinct',
    'Apply consistent type-export style across the entire project',
    'Enable TypeScript isolatedModules for stricter type export enforcement',
  ],
  curly: [
    'Always wrap if, for, while, and do bodies in curly braces',
    'Use curly braces even for single-line blocks to prevent bugs',
    'Configure this rule consistently across your entire team',
    'Consider automatic formatting tools to enforce brace style',
  ],
  'eq-eq-eq': [
    'Use === instead of == to avoid unexpected type coercion',
    'Use !== instead of != for inequality comparisons',
    'Compare values explicitly with type conversions when needed',
    'Enable strict equality across the entire codebase for consistency',
  ],
  'explicit-module-boundary-types': [
    'Add explicit return type annotations to all exported functions',
    'Document parameter and return types for public API surfaces',
    'Use TypeScript strict mode to catch implicit any types',
    'Consider using type inference only for internal implementation details',
  ],
  'max-complexity': [
    'Keep cyclomatic complexity below 10 for each function',
    'Extract complex conditional logic into well-named helper functions',
    'Use early returns to reduce nesting and branching',
    'Consider polymorphism or strategy patterns for complex switch statements',
  ],
  'max-depth': [
    'Limit nesting to 3-4 levels maximum for readability',
    'Use early returns and guard clauses to reduce nesting',
    'Extract deeply nested logic into separate functions',
    'Consider using functional approaches like map/filter/reduce',
  ],
  'max-file-size': [
    'Keep files focused on a single responsibility or feature',
    'Split large files into smaller modules with clear boundaries',
    'Use barrel files to re-export from smaller modules',
    'Aim for files under 300 lines for maintainability',
  ],
  'max-lines': [
    'Split files exceeding the line limit into focused modules',
    'Extract related functionality into separate utility files',
    'Use comments and section headers to organize longer files',
    'Review if the file has too many responsibilities',
  ],
  'max-lines-per-function': [
    'Keep functions short and focused on a single task',
    'Extract complex logic into helper functions with descriptive names',
    'Use early returns to reduce function length',
    'Aim for functions under 40 lines for readability',
  ],
  'max-params': [
    'Replace multiple parameters with an options object',
    'Use destructuring to make parameter usage clear at call sites',
    'Group related parameters into a single interface or type',
    'Aim for 3 or fewer parameters per function',
  ],
  'max-union-size': [
    'Refactor large unions into smaller semantic groups',
    'Consider using discriminated unions for related types',
    'Use enums to organize related constant values',
    'Extract repeated union types into named type aliases',
  ],
  'no-alert': [
    'Replace alert() with custom toast or notification components',
    'Use modal dialogs instead of confirm() for user decisions',
    'Implement proper form validation instead of prompt() for input',
    'Use inline messages for non-critical user feedback',
  ],
  'no-await-in-loop': [
    'Collect promises and use Promise.all() for parallel execution',
    'Use Promise.allSettled() when some failures are acceptable',
    'Use Promise.all() with chunking for rate-limited APIs',
    'Refactor sequential async operations into concurrent ones',
  ],
  'no-barrel-imports': [
    'Import directly from the source module for faster compilation',
    'Avoid barrel files (index.ts) that re-export from many modules',
    'Use path aliases instead of barrel imports for deep imports',
    'Keep import paths explicit to improve bundler tree-shaking',
  ],
  'no-circular-deps': [
    'Extract shared logic into a separate module to break cycles',
    'Use dependency injection to invert circular relationships',
    'Structure modules in a layered architecture to prevent cycles',
    'Use event-based communication to decouple circularly dependent modules',
  ],
  'no-console': [
    'Use a proper logging library (e.g., winston, pino) for structured logging',
    'Configure log levels based on environment (development vs production)',
    'Remove or disable console statements before deploying to production',
    'Use debuggers or testing tools during development instead of console',
  ],
  'no-constant-condition': [
    'Replace constant conditions with the intended variable or flag',
    'Remove dead code branches that can never execute',
    'Use boolean variables instead of literal true/false in conditions',
    'Review accidental constant conditions in debug or test code',
  ],
  'no-debugger': [
    'Remove debugger statements before committing code',
    'Use IDE breakpoints instead of debugger statements in source',
    'Configure pre-commit hooks to catch leftover debugger statements',
    'Use proper logging for production debugging scenarios',
  ],
  'no-deprecated-api': [
    'Replace deprecated APIs with their documented modern alternatives',
    'Check the API documentation for migration guides',
    'Add deprecation warnings to your own APIs when changing them',
    'Keep dependencies updated to avoid deprecated API usage',
  ],
  'no-duplicate-imports': [
    'Combine all imports from the same module into a single import statement',
    'Use named imports (import { a, b } from "./mod") instead of multiple imports',
    'Organize imports consistently across the codebase',
    'Consider using auto-fix tools to consolidate duplicate imports',
  ],
  'no-empty': [
    'Add a comment explaining why a block is intentionally empty',
    'Remove empty blocks that serve no purpose',
    'Use explicit empty implementations in test stubs',
    'Consider adding a TODO for blocks that need implementation',
  ],
  'no-empty-catch': [
    'Log the caught error or handle it appropriately',
    'Use a comment to explain why the error is intentionally ignored',
    'Consider rethrowing with additional context if appropriate',
    'Use error monitoring tools to track swallowed exceptions',
  ],
  'no-eval': [
    'Use proper JavaScript functions instead of dynamic code execution',
    'Avoid passing user input to eval() or Function()',
    'Use JSON.parse() for parsing JSON data',
    'Use object property access instead of dynamic evaluation',
  ],
  'no-explicit-any': [
    'Replace any with a specific type or unknown for safer narrowing',
    'Use generics for flexible yet type-safe code',
    'Define proper interfaces for external data structures',
    'Use unknown and type guards instead of any for dynamic data',
  ],
  'no-fallthrough': [
    'Add break, return, or throw at the end of every switch case',
    'Use // falls through comment for intentional fallthrough',
    'Consider using object maps instead of switch statements',
    'Review switch statements during code review for missing breaks',
  ],
  'no-floating-promises': [
    'Always await promises or handle them with .then()/.catch()',
    'Use the void operator to explicitly mark intentionally floating promises',
    'Enable strict promise handling in your TypeScript configuration',
    'Use no-floating-promises rule to catch unhandled promises',
  ],
  'no-implicit-coercion': [
    'Use explicit Number(), String(), or Boolean() for type conversions',
    'Avoid shorthand conversions like +x, x + "", or !!x',
    'Use parseInt() or parseFloat() with radix for number parsing',
    'Prefer explicit type conversion for code clarity and readability',
  ],
  'no-implied-eval': [
    'Pass function references to setTimeout/setInterval instead of strings',
    'Use arrow functions instead of string-based code evaluation',
    'Avoid string concatenation in timer and evaluation functions',
    'Use proper function calls instead of setTimeout("fn()") patterns',
  ],
  'no-misused-promises': [
    'Do not pass async functions to non-Promise expecting callbacks',
    'Use void return type for event handlers that do not await',
    'Wrap async operations properly when used in boolean contexts',
    'Ensure promise-returning functions are handled with await or .then()',
  ],
  'no-nested-ternary': [
    'Replace nested ternaries with if-else statements for clarity',
    'Use intermediate variables with descriptive names for conditions',
    'Extract complex conditional logic into a separate function',
    'Limit ternary expressions to a single level of nesting',
  ],
  'no-new-func': [
    'Define functions using function declarations or arrow functions',
    'Avoid dynamically constructing function bodies from strings',
    'Use closures or higher-order functions for dynamic behavior',
    'Replace new Function() with proper function definitions',
  ],
  'no-non-null-assertion': [
    'Add proper null or undefined checks instead of using the ! operator',
    'Use optional chaining (?.) for safer property access',
    'Provide default values with nullish coalescing (??)',
    'Narrow types with type guards before accessing properties',
  ],
  'no-param-reassign': [
    'Create a local copy of the parameter instead of reassigning it',
    'Use a return value to communicate changes to the caller',
    'Mark parameters as readonly to prevent accidental mutation',
    'Use spread syntax to create modified copies of object parameters',
  ],
  'no-shadow': [
    'Rename inner variables to avoid shadowing outer scope variables',
    'Use descriptive and unique variable names at each scope level',
    'Enable the no-shadow rule to catch naming conflicts early',
    'Review nested scopes for accidental variable name collisions',
  ],
  'no-sync-in-async': [
    'Replace synchronous operations with async equivalents in async functions',
    'Use fs.promises instead of fs.readFileSync in async contexts',
    'Move blocking synchronous operations outside of async functions',
    'Use worker threads for CPU-intensive synchronous work in async code',
  ],
  'no-throw-literal': [
    'Always throw Error objects: throw new Error("message")',
    'Create custom error classes for different error types',
    'Include useful context and stack traces in thrown errors',
    'Avoid throwing strings, numbers, or other non-Error values',
  ],
  'no-unsafe-assignment': [
    'Narrow any types before assigning them to typed variables',
    'Use type guards to validate dynamic data before assignment',
    'Define proper interfaces for external data before assignment',
    'Avoid assigning values from untyped sources without validation',
  ],
  'no-unsafe-regex': [
    'Rewrite regex patterns to avoid catastrophic backtracking',
    'Use atomic groups or possessive quantifiers in complex patterns',
    'Test regex patterns with diverse inputs for performance',
    'Keep regex patterns simple and avoid nested quantifiers',
  ],
  'no-unsafe-type-assertion': [
    'Use type guards instead of unsafe type assertions',
    'Validate data at runtime before casting to a specific type',
    'Use unknown as an intermediate type for safer narrowing',
    'Avoid assertions that widen types without proper validation',
  ],
  'no-unused-exports': [
    'Remove exports that are not imported anywhere in the project',
    'Consider barrel file patterns for managing public exports',
    'Use tree-shaking to eliminate unused exports in production builds',
    'Review exports during code review to prevent dead code accumulation',
  ],
  'no-unused-vars': [
    'Remove unused imports and variables to keep code clean',
    'Use tools like ESLint auto-fix to remove unused code',
    'Consider using prefix underscore for intentionally unused parameters',
    'Review unused code to ensure it was meant to be kept',
  ],
  'no-var': [
    'Replace var with const for variables that do not change',
    'Use let only for variables that need reassignment',
    'Leverage block scoping of let/const to avoid hoisting issues',
    'Use for...of loops with const instead of for with var',
  ],
  'object-shorthand': [
    'Use shorthand property syntax: { name } instead of { name: name }',
    'Use shorthand method syntax: { method() {} } instead of { method: function() {} }',
    'Apply shorthand consistently across the entire codebase',
    'Use computed property names for dynamic property assignments',
  ],
  'prefer-arrow-callback': [
    'Use arrow functions for callbacks to preserve this context',
    'Replace function() {} callbacks with () => {} syntax',
    'Use arrow functions in array methods like map, filter, and reduce',
    'Avoid arrow functions only when you need this or arguments binding',
  ],
  'prefer-async-await': [
    'Use async/await instead of .then()/.catch() chains',
    'Wrap async operations in try/catch for error handling',
    'Use Promise.all() for concurrent async operations',
    'Keep async functions simple and avoid nested await patterns',
  ],
  'prefer-at-method': [
    'Use arr.at(-1) instead of arr[arr.length - 1] for last element',
    'Use arr.at(-n) for clean negative index access',
    'Prefer .at() over manual length calculations for readability',
    'Combine .at() with optional chaining for safer access patterns',
  ],
  'prefer-const': [
    'Use const by default for variables that are not reassigned',
    'Only use let when you need to reassign a variable',
    'Consider using const for array/object references even if you modify their contents',
    'Use const with arrow functions for cleaner callbacks',
  ],
  'prefer-date-now': [
    'Use Date.now() instead of new Date().getTime() for timestamps',
    'Use performance.now() for high-resolution timing measurements',
    'Avoid creating Date objects when you only need a timestamp',
    'Prefer Date.now() for consistent millisecond timestamps',
  ],
  'prefer-includes': [
    'Use arr.includes(x) instead of arr.indexOf(x) !== -1',
    'Use includes() for membership checks on arrays and strings',
    'Combine includes() with type narrowing for cleaner conditionals',
    'Use Set.has() instead of includes() for large collections',
  ],
  'prefer-nullish-coalescing': [
    'Use ?? to check only for null/undefined, not all falsy values',
    'Replace value || default with value ?? default for 0 and "" handling',
    'Combine with optional chaining for safe property access with defaults',
    'Use ?? for configuration defaults where 0 is a valid value',
  ],
  'prefer-optional-chain': [
    'Use obj?.prop instead of obj && obj.prop for safe access',
    'Chain optional operators: obj?.prop?.method?.()',
    'Combine with nullish coalescing for default values',
    'Use optional chaining for callback invocation: callback?.()',
  ],
  'prefer-readonly': [
    'Mark arrays and objects as readonly when they are not mutated',
    'Use ReadonlyArray<T> or readonly T[] for non-mutated arrays',
    'Apply readonly to function parameters that should not be modified',
    'Use Readonly utility type for immutable object shapes',
  ],
  'prefer-rest-params': [
    'Use rest parameters (...args) instead of the arguments object',
    'Rest parameters provide proper array types without conversion',
    'Use rest parameters for variadic functions with type safety',
    'Replace arguments.length checks with rest parameter .length',
  ],
  'prefer-spread': [
    'Use spread syntax [...args] instead of fn.apply(null, args)',
    'Use spread for array concatenation: [...arr1, ...arr2]',
    'Use spread for object merging: { ...obj1, ...obj2 }',
    'Replace Array.prototype.slice.call() with spread syntax',
  ],
  'prefer-template': [
    'Use template literals instead of string concatenation with +',
    // eslint-disable-next-line no-template-curly-in-string
    'Embed expressions directly: `Hello, ${name}!`',
    'Use tagged templates for complex string formatting',
    'Use multiline template literals instead of string concatenation',
  ],
  'require-await': [
    'Add await expressions inside async functions or remove async keyword',
    'Use async keyword only when the function actually awaits',
    'Replace empty async functions with synchronous equivalents',
    'Ensure all async functions have at least one await expression',
  ],
  'sort-keys': [
    'Sort object keys alphabetically for consistency',
    'Use natural sort order for better readability of related keys',
    'Apply consistent key ordering across the entire codebase',
    'Use auto-fix tools to maintain sorted object keys',
  ],
  'use-isnan': [
    'Use Number.isNaN(x) instead of x === NaN for NaN checks',
    'NaN is the only value not equal to itself in JavaScript',
    'Use Number.isFinite() to check for finite numbers',
    'Avoid comparing values directly with the NaN literal',
  ],
  'valid-typeof': [
    'Compare typeof results to valid type strings only',
    'Use typeof x === "string", typeof x === "number", etc.',
    'Avoid comparing typeof to variable names or expressions',
    'Remember typeof null returns "object" in JavaScript',
  ],
}
