export const relatedRulesMap: Record<string, string[]> = {
  'consistent-imports': ['no-duplicate-imports', 'no-barrel-imports', 'no-unused-vars'],
  'consistent-type-exports': [
    'no-explicit-any',
    'explicit-module-boundary-types',
    'prefer-readonly',
  ],
  curly: ['no-empty', 'no-lonely-if', 'no-else-return'],
  'eq-eq-eq': ['no-implicit-coercion', 'use-isnan', 'no-compare-neg-zero'],
  'explicit-module-boundary-types': [
    'require-return-type',
    'no-explicit-any',
    'consistent-type-exports',
  ],
  'max-complexity': ['max-depth', 'max-lines-per-function', 'max-params'],
  'max-depth': ['max-complexity', 'max-lines-per-function', 'no-nested-ternary'],
  'max-file-size': ['max-lines', 'max-lines-per-function', 'no-duplicate-code'],
  'max-lines': ['max-file-size', 'max-lines-per-function', 'max-complexity'],
  'max-lines-per-function': ['max-complexity', 'max-params', 'max-depth'],
  'max-params': ['max-lines-per-function', 'max-complexity', 'prefer-rest-params'],
  'max-union-size': ['no-explicit-any', 'prefer-readonly', 'consistent-type-exports'],
  'no-alert': ['no-console', 'no-debugger', 'no-implied-eval'],
  'no-await-in-loop': ['no-sync-in-async', 'require-await', 'prefer-async-await'],
  'no-barrel-imports': ['consistent-imports', 'no-circular-deps', 'no-duplicate-imports'],
  'no-circular-deps': ['no-barrel-imports', 'consistent-imports', 'no-unused-exports'],
  'no-console': ['no-debugger', 'no-alert'],
  'no-constant-condition': ['no-unnecessary-condition', 'no-unreachable', 'no-useless-comparison'],
  'no-debugger': ['no-console', 'no-alert', 'use-logging-library'],
  'no-deprecated-api': ['no-eval', 'no-implied-eval', 'no-extend-native'],
  'no-duplicate-imports': ['no-unused-vars', 'consistent-imports'],
  'no-empty': ['no-empty-catch', 'no-empty-pattern', 'no-empty-static-block'],
  'no-empty-catch': ['no-empty', 'no-useless-catch', 'preserve-caught-error'],
  'no-eval': ['no-implied-eval', 'no-new-func', 'no-script-url'],
  'no-explicit-any': [
    'no-unsafe-assignment',
    'no-unsafe-call',
    'no-unsafe-return',
    'no-unsafe-type-assertion',
  ],
  'no-fallthrough': ['no-empty', 'no-unreachable', 'default-case'],
  'no-floating-promises': ['no-misused-promises', 'require-await', 'no-return-await'],
  'no-implicit-coercion': ['eq-eq-eq', 'prefer-number-properties', 'no-extra-boolean-cast'],
  'no-implied-eval': ['no-eval', 'no-new-func', 'no-throw-literal'],
  'no-misused-promises': ['no-floating-promises', 'no-promise-as-boolean', 'require-await'],
  'no-nested-ternary': ['max-complexity', 'max-depth', 'prefer-ternary-operator'],
  'no-new-func': ['no-eval', 'no-implied-eval', 'no-new-wrappers'],
  'no-non-null-assertion': ['no-unsafe-type-assertion', 'prefer-optional-chain', 'no-explicit-any'],
  'no-param-reassign': ['prefer-readonly', 'prefer-readonly-parameter', 'no-shadow'],
  'no-shadow': ['no-shadow-restricted-names', 'no-param-reassign', 'no-redeclare'],
  'no-sync-in-async': ['no-await-in-loop', 'require-await', 'prefer-async-await'],
  'no-throw-literal': ['prefer-promise-reject-errors', 'no-empty-catch', 'no-useless-catch'],
  'no-unsafe-assignment': ['no-unsafe-call', 'no-unsafe-member-access', 'no-explicit-any'],
  'no-unsafe-regex': ['no-eval', 'no-control-regex', 'no-empty-character-class'],
  'no-unsafe-type-assertion': ['no-non-null-assertion', 'no-explicit-any', 'no-unsafe-return'],
  'no-unused-exports': ['no-unused-vars', 'no-barrel-imports', 'no-duplicate-imports'],
  'no-unused-vars': ['no-duplicate-imports', 'no-unused-exports'],
  'no-var': ['prefer-const', 'no-const-assign'],
  'object-shorthand': ['prefer-arrow-callback', 'prefer-template', 'prefer-object-spread'],
  'prefer-arrow-callback': ['object-shorthand', 'prefer-at-context', 'prefer-template'],
  'prefer-async-await': ['no-thenable', 'no-floating-promises', 'no-return-await'],
  'prefer-at-method': ['prefer-includes', 'prefer-array-flat', 'prefer-optional-chain'],
  'prefer-const': ['no-var', 'no-const-assign'],
  'prefer-date-now': ['prefer-math-trunc', 'prefer-number-properties', 'prefer-readonly'],
  'prefer-includes': [
    'prefer-at-method',
    'prefer-object-has-own',
    'prefer-string-starts-ends-with',
  ],
  'prefer-nullish-coalescing': ['prefer-optional-chain', 'no-implicit-coercion', 'eq-eq-eq'],
  'prefer-optional-chain': [
    'prefer-nullish-coalescing',
    'no-non-null-assertion',
    'no-unsafe-optional-chaining',
  ],
  'prefer-readonly': ['prefer-readonly-parameter', 'no-param-reassign', 'no-explicit-any'],
  'prefer-rest-params': ['prefer-spread', 'no-caller', 'max-params'],
  'prefer-spread': ['prefer-rest-params', 'prefer-object-spread', 'prefer-prototype-methods'],
  'prefer-template': ['no-string-concat', 'prefer-nullish-coalescing', 'object-shorthand'],
  'require-await': ['no-async-without-await', 'no-return-await', 'no-floating-promises'],
  'sort-keys': ['no-multi-spaces', 'consistent-imports', 'consistent-type-exports'],
  'use-isnan': ['eq-eq-eq', 'valid-typeof', 'no-compare-neg-zero'],
  'valid-typeof': ['use-isnan', 'eq-eq-eq', 'no-implicit-coercion'],
}
