/**
 * Pure helper functions for the report command.
 *
 * Extracted from Report class to enable independent testing and reuse.
 * All functions are stateless — they accept parameters and return results.
 */
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'

import type { AnalysisResult, Reporter, ReporterOptions } from '../reporters/types.js'

import { ConsoleReporter } from '../reporters/console-reporter.js'
import { GitLabReporter } from '../reporters/gitlab-reporter.js'
import { HTMLReporter } from '../reporters/html-reporter.js'
import { JSONReporter } from '../reporters/json-reporter.js'
import { JUnitReporter } from '../reporters/junit-reporter.js'
import { MarkdownReporter } from '../reporters/markdown-reporter.js'
import { SARIFReporter } from '../reporters/sarif-reporter.js'
import { CLIError } from '../utils/errors.js'

export type OutputFormat = 'console' | 'gitlab' | 'html' | 'json' | 'junit' | 'markdown' | 'sarif'

export function createReporter(format: OutputFormat, options: ReporterOptions): Reporter {
  switch (format) {
    case 'gitlab': {
      return new GitLabReporter(options)
    }

    case 'html': {
      return new HTMLReporter(options)
    }

    case 'json': {
      return new JSONReporter(options)
    }

    case 'junit': {
      return new JUnitReporter(options)
    }

    case 'markdown': {
      return new MarkdownReporter(options)
    }

    case 'sarif': {
      return new SARIFReporter(options)
    }

    default: {
      return new ConsoleReporter(options)
    }
  }
}

export function validateAnalysisResult(data: AnalysisResult): boolean {
  return Boolean(data.files && data.summary && data.timestamp)
}

export async function readAnalysisFile(inputPath: string): Promise<AnalysisResult> {
  if (!existsSync(inputPath)) {
    throw new Error(`Input file not found: ${inputPath}`)
  }

  let content: string
  try {
    content = await readFile(inputPath, 'utf8')
  } catch (readError) {
    throw new Error(
      `Failed to read analysis results from ${inputPath}: ${readError instanceof Error ? readError.message : String(readError)}`,
    )
  }

  try {
    const data = JSON.parse(content) as AnalysisResult

    if (!validateAnalysisResult(data)) {
      throw new Error('Invalid analysis file format: missing required fields')
    }

    return data
  } catch (jsonError) {
    if (
      jsonError instanceof Error &&
      jsonError.message === 'Invalid analysis file format: missing required fields'
    ) {
      throw jsonError
    }

    const message = jsonError instanceof Error ? jsonError.message : 'Unknown error'
    throw CLIError.invalidInput(`Invalid JSON in input file: ${inputPath}\n  ${message}`, [
      'Validate your JSON syntax at jsonlint.com',
      'Ensure the file was generated by the analyze command',
      'Check for file corruption or incomplete download',
    ])
  }
}

export function getPlatformOpenCommand(filePath: string, platform: string): string {
  const platformCommands: Record<string, string> = {
    darwin: `open "${filePath}"`,
    win32: `start "" "${filePath}"`,
  }

  return platformCommands[platform] ?? `xdg-open "${filePath}"`
}
