export const FIXES: Record<string, string[]> = {
  'consistent-imports': [
    'Choose one style: Pick default or named imports and apply consistently',
    'Use auto-organize: Configure IDE to organize imports on save',
    'Add to config: Set import style rules in your linter configuration',
    'Review diffs: Check import consistency during code review',
  ],
  curly: [
    'Add braces: Wrap single-line if/else/for/while bodies in braces',
    'Enable auto-fix: Most linters can auto-add missing braces',
    'Use consistent style: Apply curly braces to all control flow statements',
    'Configure rule: Set curly to "all" to require braces everywhere',
  ],
  'eq-eq-eq': [
    'Replace == with ===: Use strict equality for all comparisons',
    'Use nullish checks: Use x === null || x === undefined for dual checks',
    'Auto-fix available: Most linters auto-fix == to ===',
    'Review type coercion: If you need coercion, make it explicit',
  ],
  'explicit-return-type': [
    'Add return type annotation: Specify the return type after the parameter list',
    'Use type inference for internal helpers: Only public APIs need explicit types',
    'Document complex returns: Use type aliases for complex return shapes',
    'Enable in config: Turn on explicit return types for exported functions',
  ],
  'max-complexity': [
    'Extract to helper functions: Move complex logic to smaller functions',
    'Use lookup tables: Replace if/else chains with object or map lookups',
    'Apply strategy pattern: Use polymorphism instead of long conditionals',
    'Simplify boolean logic: Apply De Morgan laws and Karnaugh maps',
  ],
  'max-depth': [
    'Extract to helper functions: Move nested logic to separate functions',
    'Use early returns: Return early to reduce nesting',
    'Use guard clauses: Check conditions upfront',
    'Apply polymorphism: Use inheritance or strategy pattern',
  ],
  'max-file-size': [
    'Split by feature: Group related code by feature, not by type',
    'Extract utilities: Move shared code to utility modules',
    'Use composition: Build complex behavior from smaller modules',
    'Review responsibilities: Each file should have one clear purpose',
  ],
  'max-lines': [
    'Split into modules: One responsibility per file',
    'Extract utilities: Move shared code to utility functions',
    'Use composition: Combine smaller pieces instead of one large file',
    'Apply single responsibility: Each file does one thing well',
  ],
  'max-lines-per-function': [
    'Extract helper functions: Break long functions into smaller ones',
    'Use guard clauses: Return early to skip unnecessary code paths',
    'Group related logic: Create well-named sub-functions for each step',
    'Reduce setup code: Extract initialization to a separate function',
  ],
  'max-params': [
    'Use an options object: Pass related parameters as a single object',
    'Apply builder pattern: Construct complex objects step by step',
    'Use partial application: Create specialized versions of functions',
    'Split the function: Break into smaller, focused functions',
  ],
  'max-union-size': [
    'Use discriminated unions: Add a kind field to distinguish members',
    'Replace with enum: Convert string unions to enums for organization',
    'Group into sub-types: Break large union into smaller type aliases',
    'Use record types: Replace union of objects with a mapped type',
  ],
  'no-alert': [
    'Use a toast library: Replace alert() with toast notifications',
    'Build a modal: Replace confirm() with a custom dialog component',
    'Create input forms: Replace prompt() with proper form components',
    'Use notification system: Implement a structured notification pattern',
  ],
  'no-array-constructor': [
    'Replace with literal: Change new Array(1, 2) to [1, 2]',
    'Use Array.from: For creating arrays from iterables or with a mapper',
    'Use Array.of: When you need to create an array from arguments',
    'Use fill: For creating arrays of a specific size with values',
  ],
  'no-await-in-loop': [
    'Use Promise.all: Collect promises and await them all at once',
    'Use Promise.allSettled: When some operations may fail independently',
    'Use map + await: Map items to promises then await Promise.all',
    'Use for-of for sequential: If sequential is needed, document why',
  ],
  'no-barrel-imports': [
    'Import directly: Change path from barrel to actual source file',
    'Remove barrel file: Delete index.ts re-exports if not needed',
    'Use package exports: Configure package.json exports field instead',
    'Limit barrel scope: Keep barrels small and focused if needed',
  ],
  'no-bitwise': [
    'Replace with logical operators: Use || and && instead of | and &',
    'Check for typos: Verify bitwise was not a typo for boolean logic',
    'Suppress if intentional: Add eslint-disable comment with explanation',
    'Encapsulate bitwise logic: Move to a named utility function',
  ],
  'no-caller': [
    'Use named functions: Replace arguments.callee with a function name',
    'Use arrow functions: Arrow functions provide lexical this binding',
    'Refactor recursion: Use a named function expression for self-reference',
    'Remove the usage: arguments.caller has no modern use case',
  ],
  'no-circular-deps': [
    'Extract shared code: Move mutual dependencies to a third module',
    'Use dependency injection: Pass dependencies as function parameters',
    'Introduce an interface: Decouple modules with an abstraction layer',
    'Restructure the graph: Create a clear module hierarchy',
  ],
  'no-cond-assign': [
    'Move assignment out: Do the assignment before the condition',
    'Use strict equality: Change = to === if comparison was intended',
    'Add extra parens: Wrap in parens if intentional to signal it',
    'Use a function call: Move the assignment into a well-named function',
  ],
  'no-console': [
    'Use a logger: Replace console.* with structured logging',
    'Throw errors: Let callers handle error conditions',
    'Return result objects: Return success/failure instead of logging',
    'Use debugging tools: Use proper debug logging that can be disabled',
  ],
  'no-console-log': [
    'Remove the call: Delete the console.log statement entirely',
    'Replace with logger: Use a proper logging library with log levels',
    'Use debug flag: Wrap in if (DEBUG) or use a debug module',
    'Add to ignore file: Configure which console methods to allow',
  ],
  'no-const-assign': [
    'Change to let: If the variable needs reassignment, use let',
    'Remove reassignment: If the variable should not change, remove the line',
    'Use array methods: For arrays, use push/map instead of reassignment',
    'Review the logic: Check if reassignment is actually needed',
  ],
  'no-debugger': [
    'Remove the statement: Delete the debugger line from source code',
    'Use IDE breakpoints: Set breakpoints in your debugger instead',
    'Add pre-commit hook: Prevent debugger from being committed',
    'Use conditional breakpoints: IDEs support conditional breakpoints',
  ],
  'no-delete-var': [
    'Set to undefined: Assign undefined instead of deleting the variable',
    'Remove the delete: Variables cannot be deleted, so remove the statement',
    'Restructure code: Redesign so deletion is not necessary',
    'Use an object: Store data in an object where delete works on properties',
  ],
  'no-dupe-keys': [
    'Remove the duplicate: Keep only one instance of the key',
    'Check the value: Decide which value the key should have',
    'Review spread merges: Object spreads can create duplicate keys',
    'Use a Map: For complex key-value storage, use Map instead',
  ],
  'no-duplicate-case': [
    'Merge the cases: Combine duplicate cases into a single case',
    'Remove the duplicate: Delete the redundant case label',
    'Use fallthrough: If intentional, merge and add a comment',
    'Review refactoring: Duplicate case often appears after code changes',
  ],
  'no-duplicate-imports': [
    'Merge import statements: Combine into a single import from that module',
    'Use auto-organize: IDE organize-imports feature merges duplicates',
    'Order imports: Place type and value imports together',
    'Review before commit: Check for duplicate imports in changed files',
  ],
  'no-else-return': [
    'Remove else keyword: The return makes else unnecessary',
    'Use early return: Return from the if block and continue after',
    'Invert the condition: Flip the if condition and return early',
    'Simplify the structure: Remove all else-after-return patterns',
  ],
  'no-empty': [
    'Add a comment: Add // intentional or explain why the block is empty',
    'Add implementation: Write the missing code for the block',
    'Use throw: In catch blocks, throw or handle the error',
    'Use noop function: Reference a named noop for intentionally empty blocks',
  ],
  'no-empty-catch': [
    'Add error logging: Log the caught error for debugging',
    'Re-throw the error: If you cannot handle it, re-throw',
    'Handle specific errors: Catch and handle specific error types',
    'Add a comment: If intentionally empty, explain why with a comment',
  ],
  'no-empty-function': [
    'Add implementation: Write the function body',
    'Use noop utility: Replace with a named noop function reference',
    'Make it abstract: For class methods, consider abstract instead',
    'Add a comment: If intentionally empty, document the reason',
  ],
  'no-eval': [
    'Replace eval() with JSON.parse(): For parsing JSON data safely',
    'Use template literals: Replace dynamic string evaluation with backticks',
    'Refactor to static code: Move dynamic logic to compile-time constructs',
    'Use Function constructor only when absolutely necessary: And validate all inputs',
  ],
  'no-explicit-any': [
    'Define a proper type: Create an interface or type for the expected shape',
    'Use unknown: Replace any with unknown and narrow with type guards',
    'Use generics: Make the function generic instead of using any',
    'Use a union type: Define the specific types that are possible',
  ],
  'no-fallthrough': [
    'Add break statement: End each case with a break',
    'Add return: Return from the case instead of breaking',
    'Add a comment: If intentional fallthrough, document with a comment',
    'Restructure to if-else: Convert switch to if-else chain if appropriate',
  ],
  'no-floating-promises': [
    'Add await: Await the promise in an async context',
    'Add .catch(): Add error handling to the promise chain',
    'Use void operator: Prefix with void if intentionally floating',
    'Return the promise: Let the caller handle the promise result',
  ],
  'no-implicit-coercion': [
    'Use Number(): Replace +x with Number(x) for number conversion',
    'Use Boolean(): Replace !!x with Boolean(x) for boolean conversion',
    'Use String(): Replace x + "" with String(x) for string conversion',
    'Be explicit: Write the conversion function name clearly',
  ],
  'no-implied-eval': [
    'Pass a function: Use setTimeout(() => fn(), 0) instead of string',
    'Use arrow functions: Replace string arguments with arrow functions',
    'Avoid Function constructor: Use closures for dynamic behavior',
    'Refactor dynamic code: Move dynamic logic to static functions',
  ],
  'no-irregular-whitespace': [
    'Replace with regular space: Remove non-breaking and irregular whitespace',
    'Enable visible whitespace: Turn on whitespace display in editor',
    'Use editor settings: Configure editor to strip irregular whitespace on save',
    'Rewrite the line: Delete and retype the line to remove hidden characters',
  ],
  'no-loop-func': [
    'Move function outside loop: Define the function before the loop',
    'Use let instead of var: Block scoping fixes closure issues',
    'Use forEach or map: Array methods handle closure correctly',
    'Extract to a helper: Create a named function outside the loop',
  ],
  'no-magic-numbers': [
    'Extract to a constant: Give the number a descriptive name',
    'Use an enum: Group related numeric values into an enum',
    'Create a config object: Collect related numbers into a configuration',
    'Add a comment: If keeping the number, explain its meaning',
  ],
  'no-misused-promises': [
    'Await the promise: Use the resolved value in the condition',
    'Add proper return type: Ensure void functions do not return promises',
    'Use void return wrapper: Wrap in a function that ignores the return',
    'Restructure the logic: Avoid passing async functions to non-async APIs',
  ],
  'no-nested-ternary': [
    'Convert to if/else: Replace nested ternaries with readable conditionals',
    'Extract a variable: Store the result of each ternary in a named variable',
    'Use a lookup object: Replace multi-way ternary with object lookup',
    'Extract a function: Move the complex expression to a named function',
  ],
  'no-new-func': [
    'Use closures: Replace new Function() with closure-based solutions',
    'Use template literals: Replace dynamic string building with templates',
    'Use a parser: For expression evaluation, use a proper parser library',
    'Refactor to static code: Move dynamic behavior to compile-time code',
  ],
  'no-non-null-assertion': [
    'Add a null check: Use if (x !== null) before accessing x',
    'Use optional chaining: Replace x!.y with x?.y or a default',
    'Use a type guard: Create a function that narrows the type',
    'Provide a default: Use nullish coalescing to supply a fallback',
  ],
  'no-param-reassign': [
    'Create a local variable: Assign the modified value to a new variable',
    'Use object spread: Create a new object instead of mutating the param',
    'Clone before modifying: Use Object.assign or spread to copy first',
    'Return a new value: Instead of mutating, return the new value',
  ],
  'no-promise-as-boolean': [
    'Await first: if (await promise) instead of if (promise)',
    'Check the resolved value: Store await result then check it',
    'Use .then() for side effects: Handle the promise result properly',
    'Add async to containing function: Ensure the function is async',
  ],
  'no-prototype-builtins': [
    'Use Object.hasOwn: Replace obj.hasOwnProperty(k) with Object.hasOwn(obj, k)',
    'Use Object.keys: Get own keys with Object.keys(obj)',
    'Use Object.getOwnPropertyDescriptor: For detailed property info',
    'Use in operator: k in obj checks the full prototype chain',
  ],
  'no-redeclare': [
    'Rename the variable: Use a different name for the second declaration',
    'Remove the duplicate: If accidental, remove the extra declaration',
    'Use block scope: Wrap in a block to create a new scope',
    'Check imports: Ensure the name is not imported twice',
  ],
  'no-self-assign': [
    'Fix the typo: Use the correct variable name on the right side',
    'Remove the statement: If truly a self-assign, it has no effect',
    'Check copy-paste errors: Self-assign often comes from copy-paste',
    'Review destructuring: Check that left and right sides differ',
  ],
  'no-shadow': [
    'Rename the inner variable: Use a different, descriptive name',
    'Rename the outer variable: Make the outer name more specific',
    'Use a prefix: Add a context prefix like innerX or localX',
    'Check catch params: Use err or error instead of shadowing e',
  ],
  'no-sparse-arrays': [
    'Use undefined explicitly: Replace empty slots with undefined',
    'Remove extra commas: Delete the comma creating the empty slot',
    'Use Array.from: Create the array with explicit values',
    'Use Array.of or fill: Construct arrays with defined values',
  ],
  'no-throw-literal': [
    'Use new Error(): Wrap the message in an Error object',
    'Create custom errors: Extend Error for domain-specific errors',
    'Always include a message: throw new Error("descriptive message")',
    'Preserve stack trace: Error objects capture the call stack',
  ],
  'no-undef': [
    'Add the missing import: Import the identifier from its module',
    'Fix the typo: Check spelling against the intended variable name',
    'Add to globals: If a legitimate global, add to the config',
    'Declare the variable: Add a const, let, or function declaration',
  ],
  'no-unreachable': [
    'Remove dead code: Delete the code after the return/throw/break',
    'Fix the control flow: Move the unreachable code before the return',
    'Review the logic: Unreachable code often indicates a design error',
    'Restructure the block: Reorganize the statements logically',
  ],
  'no-unsafe-assignment': [
    'Add a type annotation: Declare the target with a specific type',
    'Use a type guard: Narrow the source type before assigning',
    'Validate the data: Check the shape of unknown data before assigning',
    'Use unknown: Declare the source as unknown and narrow from there',
  ],
  'no-unsafe-call': [
    'Narrow the type: Use a type guard before calling the value',
    'Add a type annotation: Type the variable as a specific function',
    'Use typeof check: if (typeof fn === "function") before calling',
    'Avoid any: Remove any from the variable type declaration',
  ],
  'no-unsafe-finally': [
    'Remove return from finally: Move the return to try or catch',
    'Remove throw from finally: Let try or catch handle exceptions',
    'Keep finally minimal: Only use finally for cleanup operations',
    'Use try/catch only: If no cleanup needed, remove the finally block',
  ],
  'no-unsafe-member-access': [
    'Narrow the type: Use type guards before accessing members',
    'Add type annotation: Declare the variable with a specific type',
    'Use optional chaining: Access members with ?. to handle undefined',
    'Validate the shape: Check the object has the expected properties',
  ],
  'no-unsafe-negation': [
    'Fix the parentheses: Move the ! to negate the whole expression',
    'Use !== instead: Replace !(x === y) with x !== y',
    'Check operator precedence: Ensure negation applies to the right part',
    'Add explicit parens: Make the grouping clear with parentheses',
  ],
  'no-unsafe-regex': [
    'Simplify the pattern: Remove nested quantifiers from the regex',
    'Use atomic groups: Prevent backtracking with possessive quantifiers',
    'Add length limits: Restrict repetition with {1,n} instead of + or *',
    'Test with bad inputs: Verify the regex does not hang on adversarial input',
  ],
  'no-unsafe-return': [
    'Narrow before returning: Use type guards to validate the value',
    'Add return type annotation: Explicitly declare the return type',
    'Validate at runtime: Check the value matches the expected shape',
    'Use unknown: Return unknown and let the caller narrow the type',
  ],
  'no-unsafe-type-assertion': [
    'Use type guards: Replace as with typeof or instanceof checks',
    'Use unknown: Assert to unknown first, then narrow with validation',
    'Create a validation function: Write a runtime check that returns a type',
    'Avoid double assertions: Eliminate as unknown as T patterns',
  ],
  'no-unused-exports': [
    'Remove the export: Make the symbol module-private',
    'Check for consumers: Verify the export is not used in another package',
    'Mark as @internal: If kept for future use, document it clearly',
    'Use default export: If only one export, use default export style',
  ],
  'no-unused-vars': [
    'Remove the variable: Delete the unused declaration entirely',
    'Prefix with underscore: Use _x for intentionally unused parameters',
    'Use the variable: If it should be used, add the missing usage',
    'Check destructuring: Remove unused items from destructuring patterns',
  ],
  'no-useless-concat': [
    'Merge the strings: Combine adjacent string literals into one',
    'Use template literals: Replace + concatenation with backticks',
    'Remove empty strings: Delete empty string concatenation operands',
    'Simplify the expression: Reduce the concatenation to its essentials',
  ],
  'no-var': [
    'Replace with const: For variables that never change, use const',
    'Replace with let: For variables that do change, use let',
    'Check loop variables: Use let in for loops for block scoping',
    'Enable auto-fix: Most linters can automatically fix var to const/let',
  ],
  'object-shorthand': [
    'Use shorthand property: Change { x: x } to { x }',
    'Use shorthand method: Change { fn: function() {} } to { fn() {} }',
    'Apply consistently: Convert all object literals to use shorthand',
    'Enable auto-fix: Linters can automatically apply shorthand syntax',
  ],
  'prefer-array-find': [
    'Replace filter+index: Change arr.filter(x)[0] to arr.find(x)',
    'Use findIndex: If you need the index, use findIndex instead',
    'Handle undefined: find returns undefined when nothing matches',
    'Use a default: Chain with ?? to provide a default value',
  ],
  'prefer-array-flat': [
    'Use .flat(): Replace manual flatten code with .flat() method',
    'Specify depth: Use .flat(2) or .flat(Infinity) for deeper nesting',
    'Remove polyfill: Modern environments support .flat() natively',
    'Enable auto-fix: Linters can convert flatten patterns to .flat()',
  ],
  'prefer-async-await': [
    'Convert to async/await: Replace .then() chains with async/await',
    'Wrap in try/catch: Use try/catch for error handling with await',
    'Use top-level await: In modules, you can use await at the top level',
    'Keep Promise.all: For concurrent operations, still use Promise.all',
  ],
  'prefer-at-method': [
    'Use .at(-1): Replace arr[arr.length - 1] with arr.at(-1)',
    'Use .at(n): Access nth element from the end with .at(-n)',
    'Works on strings: Use "hello".at(-1) for string character access',
    'Polyfill if needed: For older environments, add an .at() polyfill',
  ],
  'prefer-const': [
    'Change let to const: If variable is never reassigned, use const',
    'Enable auto-fix: Linters can automatically convert let to const',
    'Review on save: Configure IDE to run const conversion on save',
    'Default to const: Start with const and only change to let if needed',
  ],
  'prefer-date-now': [
    'Use Date.now(): Replace new Date().getTime() with Date.now()',
    'Replace valueOf: Change Number(new Date()) to Date.now()',
    'Consistent usage: Use Date.now() everywhere a timestamp is needed',
    'No object allocation: Date.now() is faster as it avoids object creation',
  ],
  'prefer-default-export': [
    'Add default keyword: Change export function to export default function',
    'Keep named helpers: Non-main exports can remain named',
    'One default per file: Only the primary export should be default',
    'Update imports: Update consumers to use default import syntax',
  ],
  'prefer-for-of': [
    'Replace indexed for loop: Change for (let i=0; ...) to for (const item of arr)',
    'Remove index variable: When only the value is needed, use for-of',
    'Use entries() for index: When index is needed, use for (const [i, v] of arr.entries())',
    'Works with any iterable: Use for-of for Sets, Maps, and generators',
  ],
  'prefer-function-type': [
    'Replace interface with type: Change interface to type alias for functions',
    'Use arrow syntax: type Fn = () => void is cleaner than interface Fn',
    'Keep interfaces for objects: Use interfaces for complex object shapes',
    'Consistent convention: Choose one style and apply it everywhere',
  ],
  'prefer-includes': [
    'Replace indexOf check: Change arr.indexOf(x) !== -1 to arr.includes(x)',
    'Works on strings: Use str.includes(substr) for substring checks',
    'Returns boolean: includes() returns true/false directly',
    'Handle NaN correctly: includes() finds NaN unlike indexOf',
  ],
  'prefer-nullish-coalescing': [
    'Replace || with ??: When 0 or "" are valid values, use ??',
    'Replace ternary: Change x != null ? x : y to x ?? y',
    'Chain with optional: Combine ?. with ?? for safe access with defaults',
    'Understand the difference: ?? only triggers on null and undefined',
  ],
  'prefer-number-properties': [
    'Use Number.isNaN: Replace global isNaN() with Number.isNaN()',
    'Use Number.isFinite: Replace global isFinite() with Number.isFinite()',
    'Use Number.parseInt: Always use Number.parseInt with a radix',
    'Namespace all number ops: Use the Number namespace consistently',
  ],
  'prefer-object-has-own': [
    'Replace hasOwnProperty: Change obj.hasOwnProperty(k) to Object.hasOwn(obj, k)',
    'Replace call pattern: Change Object.prototype.hasOwnProperty.call to Object.hasOwn',
    'Works with null proto: Object.hasOwn handles null-prototype objects',
    'Enable auto-fix: Linters can convert to Object.hasOwn automatically',
  ],
  'prefer-readonly': [
    'Add readonly modifier: Mark properties set only in constructor',
    'Use Readonly utility: Apply Readonly<T> for entire object immutability',
    'Use readonly arrays: Mark array properties as readonly to prevent mutation',
    'Deep readonly: Use Readonly<Readonly<T>> for deeply nested immutable types',
  ],
  'prefer-rest-params': [
    'Use ...args syntax: Replace arguments object with rest parameters',
    'Remove Array.from: Rest params are real arrays, no conversion needed',
    'Works with arrows: Rest params work in arrow functions unlike arguments',
    'Type them properly: Use ...args: string[] for typed rest parameters',
  ],
  'prefer-spread': [
    'Replace apply: Change fn.apply(null, args) to fn(...args)',
    'Replace concat: Change [].concat(a, b) to [...a, ...b]',
    'Replace Array.from: Use [...iterable] for simple iterable conversion',
    'Works with any iterable: Spread works with Sets, Maps, and strings',
  ],
  'prefer-string-replace-all': [
    'Use .replaceAll(): Replace .replace(/pattern/g, ...) with .replaceAll()',
    'No regex needed: .replaceAll() works with plain string arguments',
    'Replace split+join: Change str.split(x).join(y) to str.replaceAll(x, y)',
    'Clearer intent: replaceAll explicitly communicates replacing all matches',
  ],
  'prefer-template': [
    // eslint-disable-next-line no-template-curly-in-string
    'Use backticks: Replace "Hello " + name with `Hello ${name}`',
    'Multiline strings: Use template literals for strings spanning lines',
    // eslint-disable-next-line no-template-curly-in-string
    'Expression interpolation: Embed any expression with ${expr}',
    'Nested templates: Use template literals inside template literals',
  ],
  'require-await': [
    'Remove async keyword: If no await is used, make the function sync',
    'Add await: If the function should be async, add missing await',
    'Check return type: Async functions return promises automatically',
    'Use promise return: Return a promise explicitly without async if needed',
  ],
  'require-return-type': [
    'Add return type: Annotate the function with its return type',
    'Use type aliases: For complex returns, define a named type',
    'Exported functions first: Prioritize adding types to public APIs',
    'Enable in config: Turn on the rule for exported function enforcement',
  ],
  'restrict-template-expressions': [
    'Convert to string: Use String(value) before interpolation',
    'Narrow the type: Ensure only safe types enter template expressions',
    'Use JSON.stringify: For debugging objects, use JSON.stringify in templates',
    'Configure allowed types: Set which types are permitted in expressions',
  ],
  'sort-keys': [
    'Sort alphabetically: Order object keys from A to Z',
    'Put computed keys last: Literal keys before computed property names',
    'Use auto-fix: Most linters sort keys automatically on save',
    'Group by prefix: Some configs group keys by naming patterns',
  ],
  'strict-boolean-expressions': [
    'Use explicit checks: Replace if (x) with if (x !== null)',
    'Check for empty: Use if (arr.length > 0) instead of if (arr)',
    'Check for NaN: Use if (!Number.isNaN(x)) instead of if (x)',
    'Handle each falsy case: Decide what to do for 0, "", NaN, and null',
  ],
  'use-isnan': [
    'Use Number.isNaN(): Replace x === NaN with Number.isNaN(x)',
    'Use global isNaN cautiously: isNaN coerces to number first',
    'Check in conditions: if (Number.isNaN(value)) to handle NaN',
    'Never compare to NaN: x === NaN is always false by definition',
  ],
  'valid-typeof': [
    'Check the string: Ensure typeof comparison uses a valid type name',
    'Valid types: "undefined", "object", "boolean", "number", "string", "function", "symbol", "bigint"',
    'Fix typos: Correct misspelled typeof comparison strings',
    'Use a constant: Store the expected type string in a constant',
  ],
}
