import * as fs from 'node:fs'
import path from 'node:path'

import type {
  AnalysisResult,
  FileAnalysisResult,
  Reporter,
  ReporterOptions,
  Violation,
} from './types.js'

const SEVERITY_ICONS: Record<Violation['severity'], string> = {
  error: '🔴',
  info: '🔵',
  warning: '🟡',
}

function getSeverityBadge(severity: Violation['severity']): string {
  return SEVERITY_ICONS[severity] || '⚪'
}

function getSeverityLabel(severity: Violation['severity']): string {
  return severity.toUpperCase()
}

function escapeMarkdown(text: string): string {
  return text.replaceAll(/[<>&`*_#[\]|]/g, String.raw`\$&`)
}

function formatCodeSnippet(source: string, line: number, _column: number): string {
  const lines = source.split('\n')
  const startLine = Math.max(0, line - 3)
  const endLine = Math.min(lines.length, line + 2)
  const snippetLines = lines.slice(startLine, endLine)

  const formatted = snippetLines
    .map((l, i) => {
      const lineNum = startLine + i + 1
      const marker = lineNum === line ? '>' : ' '
      return `${marker} ${String(lineNum).padStart(4)} | ${escapeMarkdown(l)}`
    })
    .join('\n')

  return `\`\`\`\n${formatted}\n\`\`\``
}

function formatViolationRow(violation: Violation): string {
  const badge = getSeverityBadge(violation.severity)
  const label = getSeverityLabel(violation.severity)
  const message = escapeMarkdown(violation.message)
  return `| ${badge} ${label} | ${violation.line}:${violation.column} | \`${violation.ruleId}\` | ${message} |`
}

function formatViolationsTable(violations: Violation[]): string {
  const header = '| Severity | Location | Rule | Message |'
  const separator = '|:--------:|:--------:|:----:|---------|'
  const rows = violations.map((v) => formatViolationRow(v))
  return [header, separator, ...rows].join('\n')
}

export class MarkdownReporter implements Reporter {
  readonly name = 'markdown'
  private readonly includeSource: boolean
  private readonly outputPath: string | undefined

  constructor(options: ReporterOptions = {}) {
    this.includeSource = options.includeSource ?? false
    this.outputPath = options.outputPath
  }

  format(violation: Violation): string {
    const badge = getSeverityBadge(violation.severity)
    let output = `${badge} **${violation.ruleId}** at ${violation.filePath}:${violation.line}:${violation.column} - ${violation.message}`
    
    if (violation.source) {
      output += `\n\n${formatCodeSnippet(violation.source, violation.line, violation.column)}`
    }
    
    if (violation.suggestion) {
      output += `\n\n> 💡 Suggestion: ${escapeMarkdown(violation.suggestion)}`
    }
    
    return output
  }

  report(results: AnalysisResult): void {
    const markdown = this.generateReport(results)

    if (this.outputPath) {
      this.writeToFile(markdown)
    } else {
      console.log(markdown)
    }
  }

  private generateFooter(results: AnalysisResult): string {
    return `---

*Generated by [CodeForge](https://github.com/codeforge-dev/codeforge) v${results.version ?? '0.1.0'}*`
  }

  private generateHeader(): string {
    return `# CodeForge Analysis Report

Generated on ${new Date().toISOString()}`
  }

  private generateReport(results: AnalysisResult): string {
    const sections: string[] = []

    sections.push(
      this.generateHeader(),
      this.generateSummary(results),
      this.generateViolationsByFile(results),
    )

    if (this.includeSource) {
      sections.push(this.generateSourceSnippets(results))
    }

    sections.push(this.generateFooter(results))

    return sections.filter(Boolean).join('\n\n')
  }

  private generateSourceSnippets(results: AnalysisResult): string {
    const filesWithSource = results.files.filter((f: FileAnalysisResult) =>
      f.violations.some((v: Violation) => v.source),
    )

    if (filesWithSource.length === 0) {
      return ''
    }

    const snippets = filesWithSource.flatMap((file: FileAnalysisResult) =>
      file.violations
        .filter((v: Violation) => v.source)
        .map((v: Violation) => {
          const source = v.source as string
          const snippet = formatCodeSnippet(source, v.line, v.column)
          return `#### ${file.filePath}:${v.line}\n\n${snippet}`
        }),
    )

    return `## Code Snippets\n\n${snippets.join('\n\n')}`
  }

  private generateSummary(results: AnalysisResult): string {
    const { summary } = results
    const totalViolations = summary.errorCount + summary.warningCount + summary.infoCount

    return `## Summary

| Metric | Value |
|--------|-------|
| Total Files Analyzed | ${summary.totalFiles} |
| Files with Violations | ${summary.filesWithViolations} |
| Total Violations | ${totalViolations} |
| 🔴 Errors | ${summary.errorCount} |
| 🟡 Warnings | ${summary.warningCount} |
| 🔵 Info | ${summary.infoCount} |
| Analysis Time | ${summary.totalTime.toFixed(2)}ms |`
  }

  private generateViolationsByFile(results: AnalysisResult): string {
    const filesWithViolations = results.files.filter(
      (f: FileAnalysisResult) => f.violations.length > 0,
    )

    if (filesWithViolations.length === 0) {
      return `## Violations

✅ No violations found!`
    }

    const fileSections = filesWithViolations.map((file: FileAnalysisResult) => {
      const header = `### 📄 \`${file.filePath}\`\n\n${file.violations.length} violation(s)\n\n`
      const table = formatViolationsTable(file.violations)

      const suggestions = file.violations
        .filter((v: Violation) => v.suggestion)
        .map((v: Violation) => {
          const suggestion = v.suggestion as string
          return `\n> 💡 **${v.ruleId}**: ${escapeMarkdown(suggestion)}`
        })
        .join('')

      return header + table + suggestions
    })

    return `## Violations\n\n${fileSections.join('\n\n')}`
  }

  private writeToFile(content: string): void {
    if (!this.outputPath) return

    const dir = path.dirname(this.outputPath)
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    fs.writeFileSync(this.outputPath, content, 'utf8')
  }
}
