import { describe, test, expect } from 'vitest'
import {
  DEFAULT_CI_COMMAND,
  DEFAULT_OUTPUT_FILE,
  type DangerfileOptions,
  displayDangerNextSteps,
  generateDangerfileContent,
  resolveDangerOptions,
  validateDangerOutputPath,
} from '../../../src/commands/danger-helpers.js'

function makeOptions(overrides: Partial<DangerfileOptions> = {}): DangerfileOptions {
  return {
    ciCommand: 'codeforge analyze --format json --output codeforge-results.json',
    outputFile: 'dangerfile.js',
    ...overrides,
  }
}

describe('DEFAULT_CI_COMMAND', () => {
  test('is codeforge analyze with json format', () => {
    expect(DEFAULT_CI_COMMAND).toBe('codeforge analyze --format json --output codeforge-results.json')
  })

  test('is a non-empty string', () => {
    expect(DEFAULT_CI_COMMAND.length).toBeGreaterThan(0)
  })
})

describe('DEFAULT_OUTPUT_FILE', () => {
  test('is dangerfile.js', () => {
    expect(DEFAULT_OUTPUT_FILE).toBe('dangerfile.js')
  })

  test('is a non-empty string', () => {
    expect(DEFAULT_OUTPUT_FILE.length).toBeGreaterThan(0)
  })
})

describe('generateDangerfileContent', () => {
  test('generates content with default options', () => {
    const options = makeOptions()
    const content = generateDangerfileContent(options)
    expect(content).toContain('CodeForge Dangerfile Integration')
    expect(content).toContain('auto-generated by `codeforge danger`')
  })

  test('includes the ciCommand in execSync', () => {
    const options = makeOptions({ ciCommand: 'custom-command --flag' })
    const content = generateDangerfileContent(options)
    expect(content).toContain('custom-command --flag')
  })

  test('includes the outputFile in readFileSync', () => {
    const options = makeOptions({ outputFile: 'custom-results.json' })
    const content = generateDangerfileContent(options)
    expect(content).toContain('custom-results.json')
  })

  test('uses CommonJS require syntax', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('require("child_process")')
    expect(content).toContain('require("fs")')
  })

  test('uses fail() for error severity', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('violation.severity === "error"')
    expect(content).toContain('fail(message)')
  })

  test('uses warn() for warning severity', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('violation.severity === "warning"')
    expect(content).toContain('warn(message)')
  })

  test('uses message() for info severity', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('message(message)')
  })

  test('iterates over results.files', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('for (const file of results.files)')
  })

  test('iterates over file.violations', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('for (const violation of file.violations)')
  })

  test('skips files with no violations', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('if (file.violations.length === 0) continue')
  })

  test('builds location from filePath and line', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('violation.filePath')
    expect(content).toContain('violation.line')
  })

  test('includes ruleId in message', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('violation.ruleId')
  })

  test('includes violation message', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('violation.message')
  })

  test('reports summary errors with fail()', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('summary.errorCount > 0')
    expect(content).toContain('summary.errorCount')
    expect(content).toContain('summary.filesWithViolations')
  })

  test('reports summary warnings with warn()', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('summary.warningCount > 0')
    expect(content).toContain('summary.warningCount')
  })

  test('content starts with comment header', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content.startsWith('// CodeForge Dangerfile Integration')).toBe(true)
  })

  test('returns identical output for identical inputs', () => {
    const options = makeOptions()
    const first = generateDangerfileContent(options)
    const second = generateDangerfileContent(options)
    expect(first).toBe(second)
  })

  test('different ciCommand produces different output', () => {
    const a = generateDangerfileContent(makeOptions({ ciCommand: 'cmd-a' }))
    const b = generateDangerfileContent(makeOptions({ ciCommand: 'cmd-b' }))
    expect(a).not.toBe(b)
  })

  test('different outputFile produces different output', () => {
    const a = generateDangerfileContent(makeOptions({ outputFile: 'a.json' }))
    const b = generateDangerfileContent(makeOptions({ outputFile: 'b.json' }))
    expect(a).not.toBe(b)
  })

  test('handles ciCommand with special shell characters', () => {
    const options = makeOptions({ ciCommand: 'codeforge analyze --format json --output "my file.json"' })
    const content = generateDangerfileContent(options)
    expect(content).toContain('my file.json')
  })

  test('handles outputFile with path separators', () => {
    const options = makeOptions({ outputFile: 'results/codeforge-results.json' })
    const content = generateDangerfileContent(options)
    expect(content).toContain('results/codeforge-results.json')
  })

  test('uses execSync with stdio inherit', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('stdio: "inherit"')
  })

  test('uses JSON.parse for reading results', () => {
    const content = generateDangerfileContent(makeOptions())
    expect(content).toContain('JSON.parse')
  })

  test('severity check order: error, then warning, then info', () => {
    const content = generateDangerfileContent(makeOptions())
    const errorIdx = content.indexOf('violation.severity === "error"')
    const warningIdx = content.indexOf('violation.severity === "warning"')
    expect(errorIdx).toBeLessThan(warningIdx)
  })
})

describe('resolveDangerOptions', () => {
  test('resolves with all flags provided', () => {
    const flags = { ciCommand: 'custom cmd', output: 'custom.js' }
    const result = resolveDangerOptions(flags)
    expect(result).toEqual({
      ciCommand: 'custom cmd',
      outputFile: 'custom.js',
    })
  })

  test('uses default ciCommand when not provided', () => {
    const result = resolveDangerOptions({ output: 'dangerfile.js' })
    expect(result.ciCommand).toBe(DEFAULT_CI_COMMAND)
  })

  test('uses default outputFile when not provided', () => {
    const result = resolveDangerOptions({ ciCommand: 'cmd' })
    expect(result.outputFile).toBe(DEFAULT_OUTPUT_FILE)
  })

  test('defaults all when empty object', () => {
    const result = resolveDangerOptions({})
    expect(result.ciCommand).toBe(DEFAULT_CI_COMMAND)
    expect(result.outputFile).toBe(DEFAULT_OUTPUT_FILE)
  })

  test('preserves custom ciCommand', () => {
    const result = resolveDangerOptions({ ciCommand: 'yarn lint' })
    expect(result.ciCommand).toBe('yarn lint')
  })

  test('preserves custom output', () => {
    const result = resolveDangerOptions({ output: 'my-dangerfile.js' })
    expect(result.outputFile).toBe('my-dangerfile.js')
  })

  test('handles explicit undefined ciCommand', () => {
    const result = resolveDangerOptions({ ciCommand: undefined })
    expect(result.ciCommand).toBe(DEFAULT_CI_COMMAND)
  })

  test('handles explicit undefined output', () => {
    const result = resolveDangerOptions({ output: undefined })
    expect(result.outputFile).toBe(DEFAULT_OUTPUT_FILE)
  })

  test('returns a new object on each call', () => {
    const a = resolveDangerOptions({})
    const b = resolveDangerOptions({})
    expect(a).toEqual(b)
    expect(a).not.toBe(b)
  })

  test('does not mutate input flags', () => {
    const flags = { ciCommand: 'test' }
    const copy = { ...flags }
    resolveDangerOptions(flags)
    expect(flags).toEqual(copy)
  })
})

describe('validateDangerOutputPath', () => {
  test('returns valid for .js file', () => {
    const result = validateDangerOutputPath('dangerfile.js')
    expect(result.valid).toBe(true)
  })

  test('returns valid for .ts file', () => {
    const result = validateDangerOutputPath('dangerfile.ts')
    expect(result.valid).toBe(true)
  })

  test('returns valid for nested .js file', () => {
    const result = validateDangerOutputPath('danger/dangerfile.js')
    expect(result.valid).toBe(true)
  })

  test('returns invalid for empty string', () => {
    const result = validateDangerOutputPath('')
    expect(result.valid).toBe(false)
    expect(result.error).toBeDefined()
  })

  test('returns invalid for whitespace only', () => {
    const result = validateDangerOutputPath('   ')
    expect(result.valid).toBe(false)
  })

  test('returns invalid for absolute path', () => {
    const result = validateDangerOutputPath('/tmp/dangerfile.js')
    expect(result.valid).toBe(false)
    expect(result.error).toContain('Absolute paths')
  })

  test('returns invalid for non-js non-ts file', () => {
    const result = validateDangerOutputPath('dangerfile.py')
    expect(result.valid).toBe(false)
    expect(result.error).toContain('.js or .ts')
  })

  test('returns invalid for no extension', () => {
    const result = validateDangerOutputPath('dangerfile')
    expect(result.valid).toBe(false)
  })

  test('returns valid for relative path with .js', () => {
    const result = validateDangerOutputPath('./danger/dangerfile.js')
    expect(result.valid).toBe(true)
  })

  test('error is undefined when valid', () => {
    const result = validateDangerOutputPath('dangerfile.js')
    expect(result.error).toBeUndefined()
  })

  test('error is string when invalid', () => {
    const result = validateDangerOutputPath('')
    expect(typeof result.error).toBe('string')
  })

  test('returns same result for same input', () => {
    const a = validateDangerOutputPath('test.js')
    const b = validateDangerOutputPath('test.js')
    expect(a).toEqual(b)
  })
})

describe('displayDangerNextSteps', () => {
  test('calls logFn multiple times', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    expect(lines.length).toBeGreaterThan(3)
  })

  test('includes next steps header', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    const output = lines.join('\n')
    expect(output).toContain('Next steps')
  })

  test('mentions installing Danger.js', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    const output = lines.join('\n')
    expect(output).toContain('npm install danger')
  })

  test('mentions reviewing the Dangerfile', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    const output = lines.join('\n')
    expect(output).toContain('Dangerfile')
  })

  test('mentions CI pipeline', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    const output = lines.join('\n')
    expect(output).toContain('CI')
  })

  test('mentions codeforge installation', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    const output = lines.join('\n')
    expect(output).toContain('codeforge')
  })

  test('returns void', () => {
    const result = displayDangerNextSteps(() => {})
    expect(result).toBeUndefined()
  })

  test('produces consistent output across calls', () => {
    const lines1: string[] = []
    const lines2: string[] = []
    displayDangerNextSteps((msg) => lines1.push(msg))
    displayDangerNextSteps((msg) => lines2.push(msg))
    expect(lines1).toEqual(lines2)
  })

  test('first line is blank separator', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    expect(lines[0]).toBe('')
  })

  test('all step numbers are present', () => {
    const lines: string[] = []
    displayDangerNextSteps((msg) => lines.push(msg))
    const output = lines.join('\n')
    expect(output).toContain('1.')
    expect(output).toContain('2.')
    expect(output).toContain('3.')
    expect(output).toContain('4.')
  })
})

describe('DangerfileOptions type', () => {
  test('makeOptions returns valid defaults', () => {
    const opts = makeOptions()
    expect(opts.ciCommand).toBe('codeforge analyze --format json --output codeforge-results.json')
    expect(opts.outputFile).toBe('dangerfile.js')
  })

  test('makeOptions allows overriding ciCommand', () => {
    const opts = makeOptions({ ciCommand: 'custom' })
    expect(opts.ciCommand).toBe('custom')
    expect(opts.outputFile).toBe('dangerfile.js')
  })

  test('makeOptions allows overriding outputFile', () => {
    const opts = makeOptions({ outputFile: 'other.js' })
    expect(opts.outputFile).toBe('other.js')
  })

  test('makeOptions allows overriding all', () => {
    const opts = makeOptions({ ciCommand: 'cmd', outputFile: 'out.js' })
    expect(opts).toEqual({ ciCommand: 'cmd', outputFile: 'out.js' })
  })
})

describe('integration - function combinations', () => {
  test('resolveDangerOptions result works with generateDangerfileContent', () => {
    const options = resolveDangerOptions({ ciCommand: 'test-cmd', output: 'test.js' })
    const content = generateDangerfileContent(options)
    expect(content).toContain('test-cmd')
    expect(content).toContain('test.js')
  })

  test('resolveDangerOptions result works with validateDangerOutputPath', () => {
    const options = resolveDangerOptions({ output: 'dangerfile.js' })
    const validation = validateDangerOutputPath(options.outputFile)
    expect(validation.valid).toBe(true)
  })

  test('full workflow: resolve -> generate -> display', () => {
    const options = resolveDangerOptions({
      ciCommand: 'codeforge analyze --format json',
      output: 'danger/dangerfile.js',
    })
    const content = generateDangerfileContent(options)
    const lines: string[] = []

    expect(content).toContain('codeforge analyze --format json')
    expect(content).toContain('danger/dangerfile.js')
    expect(content).toContain('fail(message)')
    expect(content).toContain('warn(message)')

    displayDangerNextSteps((msg) => lines.push(msg))
    expect(lines.join('\n')).toContain('npm install danger')
  })
})
