export const RULE_SUGGESTIONS = {
  consistentTypeExports: 'Use type-only exports for types and value exports for runtime values.',
  curly: 'Consistently use curly braces for all control flow statements to prevent bugs.',
  eqEqEq: 'Use === instead of == to avoid unexpected type coercion.',
  explicitModuleBoundaryTypes: 'Add explicit return type annotations to exported functions.',
  maxFileSize: 'Split large files into smaller, focused modules.',
  maxUnionSize:
    'Reduce union type size by extracting shared patterns or using discriminated unions.',
  noAlert:
    'Replace alert(), confirm(), and prompt() with custom UI components or toast notifications.',
  noArrayConstructor: ' Use array literal [] instead of new Array().',
  noArrayDestructuring: ' For large arrays, use concat() or slice() instead of spread operator.',
  noAsyncPromiseExecutor: ' Use the async function directly or refactor the executor.',
  noAsyncWithoutAwait: ' Remove the async keyword if no await is present.',
  noBitwise:
    'Avoid bitwise operators unless explicitly needed for bit manipulation. They often indicate typos.',
  noCaseDeclarations: ' Move the declaration to an outer block.',
  noCollectionSizeMischeck:
    'Remove comparisons of collection sizes (.length, .size) with negative numbers. Sizes are always non-negative.',
  noConfusingVoidExpression: 'Avoid void expressions in positions where a value is expected.',
  noConsole: 'Use a logging library like winston or pino for production code.',
  noConsoleLog: 'Use a logging library like winston or pino for production code.',
  noConstantBinaryExpression:
    'Simplify constant binary expressions that always evaluate to the same value.',
  noConstantCondition: 'Avoid constant conditions in if/while/for that are always true or false.',
  noConstAssign: 'Do not reassign const variables. Use let if reassignment is needed.',
  noConstructorReturn:
    'Remove return statements from constructors. Constructors should not return values.',
  noControlRegex: String.raw`Escape control characters in regex or use \x01 notation explicitly.`,
  noDebugger: 'Remove debugger statements. Use a proper debugging tool or logging library.',
  noDeleteVar: 'Avoid delete on variables. Set to undefined or null instead.',
  noDeprecatedImports:
    'Replace deprecated imports with their recommended alternatives. Check the package documentation.',
  noDivRegex: String.raw`Fix regex starting with = by escaping the equals sign: /=/ should be /\=/.`,
  noDupeArgs: 'Remove duplicate parameter names from function declarations.',
  noDupeKeys: 'Remove duplicate keys in object literals to avoid unexpected behavior.',
  noDuplicateCase: 'Remove duplicate case labels in switch statements.',
  noDuplicateCode: 'Extract duplicated code into shared functions or modules.',
  noDuplicateElseIf: 'Remove duplicate conditions in else-if chains.',
  noDuplicateImports: 'Merge duplicate import statements for the same module.',
  noElseReturn: 'Remove else after return. The else is unnecessary when if returns.',
  noEmpty: 'Add meaningful code to empty blocks or remove them entirely.',
  noEmptyCharacterClass:
    'Fix empty character class in regex. Use [] to match literally or add a pattern.',
  noEmptyPattern: 'Provide meaningful destructuring patterns instead of empty ones.',
  noEmptyStaticBlock: 'Add code to empty static blocks or remove them.',
  noEval: 'Avoid eval() for security. Use JSON.parse() for JSON or Function() constructor.',
  noExAssign: 'Avoid reassigning catch clause parameters. Use a local variable instead.',
  noExplicitAny: 'Replace any with a specific type. Use unknown for truly dynamic values.',
  noExtendNative: 'Avoid extending native prototypes. Use utility functions or wrapper classes.',
  noExtraBooleanCast: 'Remove unnecessary boolean casts like !! or Boolean() in boolean contexts.',
  noFallthrough: 'Add break, return, or throw to each case, or comment intentional fallthrough.',
  noFloatingPromises: 'Add await, .catch(), or void operator to handle floating promises.',
  noFuncAssign: 'Avoid reassigning function declarations. Use a different variable name.',
  noGlobalAssign: 'Avoid modifying global variables. Use local variables instead.',
  noImplicitCoercion:
    'Use explicit type conversion: String(), Number(), Boolean() instead of shortcuts.',
  noImportAssign: 'Avoid reassigning imported bindings. Use local variables for mutations.',
  noInferrableTypes:
    'Remove explicitly typed initializers that can be inferred: const x: number = 1.',
  noInvalidRegexp: 'Fix the invalid regular expression pattern.',
  noIrregularWhitespace: 'Replace irregular whitespace characters with standard spaces or tabs.',
  noIterator:
    'Avoid the deprecated __iterator__ property. Use Symbol.iterator and for...of instead.',
  noLabelVar: 'Avoid label names that shadow variable names to prevent confusion.',
  noLonelyIf: 'Merge the single if statement into the parent else clause for clarity.',
  noLoopFunc: 'Move function declarations outside of loops, or use let for closure variables.',
  noLossOfPrecision: 'Avoid number literals that exceed JavaScript safe integer range.',
  noMisleadingCharacterClass:
    'Use explicit character ranges in regex to avoid matching unexpected characters.',
  noMisusedPromises: 'Use void return for functions that should not return promises.',
  noMultiSpaces: 'Remove extra whitespace. Configure editor to trim trailing spaces.',
  noNamespace:
    'Use ES modules (import/export) instead of TypeScript namespaces for better tree-shaking and standards compliance.',
  noNestedTernary: 'Refactor nested ternary expressions into if-else or separate variables.',
  noNewFunc: 'Avoid new Function(). Use regular function declarations for better debuggability.',
  noNewNativeNonconstructor: 'Avoid new with Symbol and BigInt. Call them directly without new.',
  noNewWrappers:
    'Use primitives directly: string, number, boolean instead of new String(), new Number(), new Boolean().',
  noNonNullAssertion: 'Add proper null checks instead of using the ! non-null assertion operator.',
  noNonoctalDecimalEscape: String.raw`Use \0 for null escape instead of \8 or \9 which are deprecated.`,
  noObjCalls: 'Remove function call on non-callable objects like Math() or JSON().',
  noObjectConstructor: 'Use object literal {} instead of new Object().',
  noOctal: 'Use decimal or hexadecimal literals instead of octal (0-prefixed) numbers.',
  noParamReassign: 'Avoid reassigning function parameters. Use a local variable instead.',
  noPromiseAsBoolean: 'Use await or .then() to resolve promises before boolean checks.',
  noPrototypeBuiltins:
    'Use Object.hasOwnProperty.call() or Object.keys() instead of obj.hasOwnProperty().',
  noRedeclare: 'Avoid redeclaring variables in the same scope. Use different names.',
  noRedundantBoolean:
    'Remove redundant boolean comparisons (x === true). Use the expression directly or with negation (!).',
  noRegexSpaces: String.raw`Use explicit space quantifiers in regex: {n} or \s instead of literal spaces.`,
  noReturnAssign: 'Wrap return assignments in parentheses or use separate statements for clarity.',
  noReturnAwait: 'Remove unnecessary await in return statements. Return the promise directly.',
  noSelfAssign: 'Remove self-assignments like x = x which have no effect.',
  noSequences: 'Avoid comma operator in expressions. Use separate statements instead.',
  noSetterReturn: 'Remove return values from setter methods. Setters should not return.',
  noShadow: 'Rename shadowed variables to avoid confusion with outer scope.',
  noShadowRestrictedNames:
    'Rename variables that shadow restricted names like undefined, NaN, Infinity.',
  noSimplifiablePattern: 'Simplify redundant pattern matching expressions.',
  noSparseArrays: 'Avoid sparse arrays with missing elements. Use undefined explicitly if needed.',
  noStringConcat: 'Use template literals instead of string concatenation for better readability.',
  noTemplateCurlyInString:
    'Use backticks (template literals) instead of quotes when using template expression syntax.',
  noThenable: 'Avoid returning thenable objects (then method) from async functions.',
  noThisBeforeSuper: 'Access this only after calling super() in derived class constructors.',
  noThrowLiteral: 'Throw Error objects instead of string literals: throw new Error("message").',
  noThrowSync: 'Avoid throwing errors in async functions. Use rejected promises instead.',
  noTypeOnlyReturn: 'Avoid type-only return values. Use proper runtime values.',
  noUnassignedVars: 'Initialize variables when declaring them, or use a different pattern.',
  noUndef: 'Ensure all variables are defined before use. Check for typos in variable names.',
  noUnexpectedMultiline: 'Add semicolons or reorder code to avoid unexpected multiline behavior.',
  noUnfinishedTodos: 'Remove or update unfinished TODO comments.',
  noUnnecessaryCondition:
    'Remove conditions that are always true or false based on type information.',
  noUnnecessaryEscapeInRegexp: 'Remove unnecessary escape characters in regex patterns.',
  noUnnecessaryPolyfills:
    'Remove polyfill imports for APIs that are natively supported in modern JavaScript engines.',
  noUnnecessaryQualifier: 'Remove unnecessary type qualifiers when they can be inferred.',
  noUnnecessarySlice: 'Use the full array/string instead of slicing from 0 or to the end.',
  noUnnecessaryStringConcat: 'Use template literals instead of concatenating string literals.',
  noUnnecessaryTemplateExpression:
    // eslint-disable-next-line no-template-curly-in-string
    'Remove unnecessary template expression interpolation: `${x}` → x.',
  noUnnecessaryTypeArguments: 'Remove explicit type arguments that can be inferred by TypeScript.',
  noUnneededTernary: 'Simplify ternary to direct value: x ? true : false → !!x or Boolean(x).',
  noUnreachable: 'Remove code after return, throw, break, or continue statements.',
  noUnsafeAssignment: 'Add proper type annotations when assigning values from untyped sources.',
  noUnsafeCall: 'Add proper type annotations to avoid unsafe calls on any-typed values.',
  noUnsafeDeclarationMerging: 'Avoid declaring interfaces and classes with the same name.',
  noUnsafeFinally: 'Avoid return, throw, break, or continue inside finally blocks.',
  noUnsafeMemberAccess:
    'Add proper type annotations to avoid unsafe member access on any-typed values.',
  noUnsafeNegation:
    'Add parentheses to clarify negation of the entire expression, not just the left operand.',
  noUnsafeOptionalChaining: 'Add null checks before optional chaining in operand positions.',
  noUnsafeRegex: 'Avoid unsafe regex patterns that can cause catastrophic backtracking.',
  noUnsafeReturn: 'Add proper return type annotations to avoid returning any-typed values.',
  noUnsafeTypeAssertion: 'Use proper type narrowing instead of unsafe type assertions.',
  noUnusedExpressions: 'Assign expression results to variables or use them in statements.',
  noUnusedLabels: 'Remove unused labels from the code.',
  noUnusedPrivateMembers: 'Remove unused private class members or use them.',
  noUnusedVars: 'Remove unused variables, or prefix with underscore if intentionally unused.',
  noUselessAssignment: 'Remove assignments where the value is immediately overwritten or unused.',
  noUselessBackreference: 'Fix regex backreferences that can never match.',
  noUselessCatch: 'Remove try-catch blocks that only rethrow. Let the error propagate naturally.',
  noUselessComparison: 'Remove comparisons that always evaluate to the same result.',
  noUselessConcat: 'Remove unnecessary string concatenation. Use a single string literal.',
  noUselessConstructor:
    'Remove constructor delegating to parent. The default constructor handles this.',
  noUselessEscape: 'Remove unnecessary escape characters in strings and regex.',
  noUselessFallbackInSpread: 'Remove unnecessary fallback in spread: {...obj} || {} → {...obj}.',
  noUselessUndefined:
    'Remove unnecessary undefined initializations. Variables default to undefined.',
  noUtilityTruthiness:
    'Use explicit comparisons like .length > 0 or .size !== 0 instead of relying on truthiness.',
  noVar: 'Use let or const instead of var for block-scoped variables.',
  noVarRequires: 'Use import statements instead of require() for ES module compatibility.',
  noVoid: 'Avoid void operator. Use undefined directly or restructure the code.',
  noWith: 'Replace with statements with explicit variable references for clarity.',
  objectShorthand: 'Use shorthand property and method syntax in objects: { name, method() {} }.',
  preferArrayFlat: 'Use Array.flat() instead of manual flattening with reduce or concat.',
  preferArrowCallback:
    'Use arrow functions for callbacks: () => expr instead of function() { return expr }.',
  preferAsyncAwait: 'Use async/await instead of raw Promise chains for better readability.',
  preferAtContext: 'Use @context decorator for GraphQL context injection.',
  preferAtMethod: 'Use method decorators for consistent API patterns.',
  preferConst: 'Use const for variables that are never reassigned.',
  preferDateNow: 'Use Date.now() instead of new Date().getTime() for current timestamp.',
  preferEnumInitializers: 'Provide explicit values for all enum members for clarity.',
  preferExponentiationOperator: 'Use the ** operator instead of Math.pow() for exponentiation.',
  preferFunctionType: 'Use interface with call signature instead of type with new for functions.',
  preferIncludes: 'Use array.includes() instead of indexOf() for membership checks.',
  preferLiteralEnumMember: 'Use literal values for enum members to enable reverse mapping.',
  preferNullishCoalescing: 'Use the ?? operator instead of || for null/undefined fallbacks.',
  preferNumericLiterals:
    'Use binary (0b), octal (0o), or hex (0x) literals for non-decimal numbers.',
  preferObjectHasOwn: 'Use Object.hasOwn() instead of Object.prototype.hasOwnProperty.call().',
  preferObjectSpread: 'Use object spread (...) instead of Object.assign() for better readability.',
  preferOptionalChain: 'Use optional chaining (?.) for safer property access.',
  preferPromiseRejectErrors:
    'Reject promises with Error objects: reject(new Error("msg")) instead of reject("msg").',
  preferPrototypeMethods: 'Use prototype methods instead of arrow functions in class properties.',
  preferReadonly: 'Mark class properties as readonly when they are never reassigned.',
  preferReadonlyParameter: 'Mark function parameters as readonly when they are not modified.',
  preferRegexLiterals: 'Use regex literals (/pattern/) instead of new RegExp() when possible.',
  preferRegexpExec: 'Use RegExp.exec() instead of String.match() with global regex.',
  preferRestParams: 'Use rest parameters (...args) instead of the arguments object.',
  preferSingleBooleanReturn:
    'Return the boolean expression directly instead of using if-else to return true/false.',
  preferSpread: 'Use the spread operator (...) instead of Function.prototype.apply().',
  preferStringReplaceAll: 'Use String.replaceAll() instead of String.replace() with global regex.',
  preferStringSlice: 'Use String.slice() instead of String.substring() for consistency.',
  preferStringStartsEndsWith:
    'Use startsWith()/endsWith() instead of indexOf() or regex for prefix/suffix checks.',
  preferTemplate: 'Use template literals instead of string concatenation with +.',
  preferTernaryOperator:
    'Use ternary operator for simple conditional assignments instead of if-else.',
  preserveCaughtError: 'Log or handle caught errors instead of silently ignoring them.',
  requireAwait: 'Add await inside async functions or remove the async keyword.',
  requireReturnType: 'Add explicit return type annotations to functions for better type safety.',
  requireYield: 'Add a yield statement to generator functions or remove the * marker.',
  restrictTemplateExpressions:
    'Restrict types used in template expressions to prevent unexpected stringification.',
  sortKeys: 'Sort object keys consistently for better readability and diff comparison.',
  useIsnan: 'Use Number.isNaN() instead of comparing to NaN, which is never equal.',
  useLoggingLibrary: 'Use a logging library instead of debugger statements.',
  useStrictEquality: 'Use strict equality (===) to avoid unexpected type coercion.',
  validTypeof:
    'Compare typeof results against valid type strings: undefined, boolean, number, string, object, function, symbol, bigint.',
} as const
