import { describe, it, expect } from 'vitest'
import { UnionFindUndo } from '../../src/utils/union-find-undo.js'

describe('UnionFindUndo', () => {
  it('initial state (all singletons)', () => {
    const dsu = new UnionFindUndo(5)
    expect(dsu.componentCount).toBe(5)
    expect(dsu.size).toBe(5)
    expect(dsu.find(0)).toBe(0)
    expect(dsu.find(1)).toBe(1)
    expect(dsu.find(2)).toBe(2)
    expect(dsu.find(3)).toBe(3)
    expect(dsu.find(4)).toBe(4)
    expect(dsu.getSize(0)).toBe(1)
    expect(dsu.getSize(1)).toBe(1)
    expect(dsu.getSize(2)).toBe(1)
    expect(dsu.getSize(3)).toBe(1)
    expect(dsu.getSize(4)).toBe(1)
  })

  it('union two elements', () => {
    const dsu = new UnionFindUndo(5)
    const result = dsu.union(0, 1)
    expect(result).toBe(true)
    expect(dsu.componentCount).toBe(4)
    expect(dsu.connected(0, 1)).toBe(true)
    expect(dsu.find(0)).toBe(dsu.find(1))
  })

  it('union creates correct component count', () => {
    const dsu = new UnionFindUndo(10)
    dsu.union(0, 1)
    expect(dsu.componentCount).toBe(9)
    dsu.union(2, 3)
    expect(dsu.componentCount).toBe(8)
    dsu.union(4, 5)
    expect(dsu.componentCount).toBe(7)
    dsu.union(0, 2)
    expect(dsu.componentCount).toBe(6)
    dsu.union(0, 4)
    expect(dsu.componentCount).toBe(5)
  })

  it('find returns correct representative', () => {
    const dsu = new UnionFindUndo(6)
    expect(dsu.find(0)).toBe(0)
    expect(dsu.find(1)).toBe(1)
    expect(dsu.find(2)).toBe(2)
    dsu.union(0, 2)
    expect(dsu.find(0) === dsu.find(2)).toBe(true)
    dsu.union(1, 3)
    expect(dsu.find(1) === dsu.find(3)).toBe(true)
    dsu.union(0, 1)
    expect(dsu.find(0) === dsu.find(1) && dsu.find(1) === dsu.find(2) && dsu.find(2) === dsu.find(3)).toBe(true)
  })

  it('connected works correctly', () => {
    const dsu = new UnionFindUndo(6)
    expect(dsu.connected(0, 1)).toBe(false)
    expect(dsu.connected(2, 3)).toBe(false)
    dsu.union(0, 1)
    expect(dsu.connected(0, 1)).toBe(true)
    expect(dsu.connected(0, 2)).toBe(false)
    dsu.union(2, 3)
    expect(dsu.connected(2, 3)).toBe(true)
    expect(dsu.connected(0, 2)).toBe(false)
    dsu.union(1, 2)
    expect(dsu.connected(0, 3)).toBe(true)
  })

  it('GetSize after unions', () => {
    const dsu = new UnionFindUndo(8)
    expect(dsu.getSize(0)).toBe(1)
    expect(dsu.getSize(1)).toBe(1)
    dsu.union(0, 1)
    expect(dsu.getSize(0)).toBe(2)
    expect(dsu.getSize(1)).toBe(2)
    dsu.union(2, 3)
    dsu.union(0, 2)
    expect(dsu.getSize(0)).toBe(4)
    expect(dsu.getSize(1)).toBe(4)
    expect(dsu.getSize(2)).toBe(4)
    expect(dsu.getSize(3)).toBe(4)
    dsu.union(4, 5)
    dsu.union(4, 6)
    expect(dsu.getSize(4)).toBe(3)
  })

  it('undo single union', () => {
    const dsu = new UnionFindUndo(5)
    dsu.union(0, 1)
    expect(dsu.componentCount).toBe(4)
    expect(dsu.connected(0, 1)).toBe(true)
    dsu.undo()
    expect(dsu.componentCount).toBe(5)
    expect(dsu.connected(0, 1)).toBe(false)
    expect(dsu.find(0)).toBe(0)
    expect(dsu.find(1)).toBe(1)
    expect(dsu.getSize(0)).toBe(1)
    expect(dsu.getSize(1)).toBe(1)
  })

  it('undo multiple unions', () => {
    const dsu = new UnionFindUndo(10)
    dsu.union(0, 1)
    dsu.union(2, 3)
    dsu.union(4, 5)
    dsu.union(6, 7)
    expect(dsu.componentCount).toBe(6)
    dsu.undo()
    expect(dsu.componentCount).toBe(7)
    expect(dsu.connected(6, 7)).toBe(false)
    dsu.undo()
    expect(dsu.componentCount).toBe(8)
    expect(dsu.connected(4, 5)).toBe(false)
    dsu.undo()
    expect(dsu.componentCount).toBe(9)
    dsu.undo()
    expect(dsu.componentCount).toBe(10)
  })

  it('snapshot and rollback to earlier state', () => {
    const dsu = new UnionFindUndo(8)
    dsu.union(0, 1)
    dsu.union(2, 3)
    dsu.union(4, 5)
    const snapshot = dsu.snapshot()
    expect(snapshot).toBe(3)
    expect(dsu.componentCount).toBe(5)
    dsu.union(0, 2)
    dsu.union(4, 6)
    expect(dsu.componentCount).toBe(3)
    dsu.rollback(snapshot)
    expect(dsu.componentCount).toBe(5)
    expect(dsu.connected(0, 1)).toBe(true)
    expect(dsu.connected(2, 3)).toBe(true)
    expect(dsu.connected(4, 5)).toBe(true)
    expect(dsu.connected(0, 2)).toBe(false)
    expect(dsu.connected(4, 6)).toBe(false)
  })

  it('snapshot/rollback with intermediate unions', () => {
    const dsu = new UnionFindUndo(6)
    const snap1 = dsu.snapshot()
    expect(snap1).toBe(0)
    dsu.union(0, 1)
    const snap2 = dsu.snapshot()
    expect(snap2).toBe(1)
    dsu.union(2, 3)
    const snap3 = dsu.snapshot()
    expect(snap3).toBe(2)
    dsu.union(0, 2)
    dsu.union(4, 5)
    expect(dsu.componentCount).toBe(2)
    dsu.rollback(snap3)
    expect(dsu.componentCount).toBe(4)
    expect(dsu.connected(0, 2)).toBe(false)
    dsu.rollback(snap2)
    expect(dsu.componentCount).toBe(5)
    expect(dsu.connected(2, 3)).toBe(false)
    dsu.rollback(snap1)
    expect(dsu.componentCount).toBe(6)
  })

  it('union returns false for same-set elements', () => {
    const dsu = new UnionFindUndo(5)
    dsu.union(0, 1)
    const result1 = dsu.union(0, 1)
    expect(result1).toBe(false)
    const result2 = dsu.union(1, 0)
    expect(result2).toBe(false)
    dsu.union(2, 3)
    dsu.union(0, 2)
    const result3 = dsu.union(1, 3)
    expect(result3).toBe(false)
    const result4 = dsu.union(2, 0)
    expect(result4).toBe(false)
  })

  it('complex sequence: union, snapshot, more unions, rollback, verify', () => {
    const dsu = new UnionFindUndo(10)
    dsu.union(0, 1)
    dsu.union(2, 3)
    dsu.union(4, 5)
    const snap1 = dsu.snapshot()
    expect(dsu.componentCount).toBe(7)
    expect(dsu.getSize(0)).toBe(2)
    expect(dsu.getSize(2)).toBe(2)
    expect(dsu.getSize(4)).toBe(2)
    dsu.union(0, 2)
    dsu.union(6, 7)
    dsu.union(0, 4)
    expect(dsu.componentCount).toBe(4)
    expect(dsu.getSize(0)).toBe(6)
    expect(dsu.getSize(6)).toBe(2)
    dsu.rollback(snap1)
    expect(dsu.componentCount).toBe(7)
    expect(dsu.getSize(0)).toBe(2)
    expect(dsu.getSize(4)).toBe(2)
    expect(dsu.connected(0, 2)).toBe(false)
    expect(dsu.connected(6, 7)).toBe(false)
    dsu.union(0, 2)
    expect(dsu.getSize(0)).toBe(4)
    expect(dsu.componentCount).toBe(6)
  })

  it('all elements connected into one set', () => {
    const dsu = new UnionFindUndo(7)
    expect(dsu.componentCount).toBe(7)
    dsu.union(0, 1)
    dsu.union(2, 3)
    dsu.union(4, 5)
    expect(dsu.componentCount).toBe(4)
    dsu.union(0, 2)
    expect(dsu.componentCount).toBe(3)
    dsu.union(0, 4)
    expect(dsu.componentCount).toBe(2)
    dsu.union(0, 6)
    expect(dsu.componentCount).toBe(1)
    expect(dsu.connected(0, 1)).toBe(true)
    expect(dsu.connected(1, 2)).toBe(true)
    expect(dsu.connected(2, 3)).toBe(true)
    expect(dsu.connected(3, 4)).toBe(true)
    expect(dsu.connected(4, 5)).toBe(true)
    expect(dsu.connected(5, 6)).toBe(true)
    expect(dsu.connected(0, 6)).toBe(true)
    expect(dsu.getSize(0)).toBe(7)
  })

  it('throws error for invalid index in constructor', () => {
    expect(() => new UnionFindUndo(-1)).toThrow(RangeError)
    expect(() => new UnionFindUndo(1.5)).toThrow(RangeError)
    expect(() => new UnionFindUndo(Infinity)).toThrow(RangeError)
  })

  it('throws error for invalid index in find', () => {
    const dsu = new UnionFindUndo(5)
    expect(() => dsu.find(-1)).toThrow(RangeError)
    expect(() => dsu.find(5)).toThrow(RangeError)
  })

  it('throws error for invalid index in union', () => {
    const dsu = new UnionFindUndo(5)
    expect(() => dsu.union(-1, 0)).toThrow(RangeError)
    expect(() => dsu.union(0, 5)).toThrow(RangeError)
  })

  it('throws error for invalid index in connected', () => {
    const dsu = new UnionFindUndo(5)
    expect(() => dsu.connected(-1, 0)).toThrow(RangeError)
    expect(() => dsu.connected(0, 5)).toThrow(RangeError)
  })

  it('throws error for invalid index in getSize', () => {
    const dsu = new UnionFindUndo(5)
    expect(() => dsu.getSize(-1)).toThrow(RangeError)
    expect(() => dsu.getSize(5)).toThrow(RangeError)
  })

  it('throws error for undo when nothing to undo', () => {
    const dsu = new UnionFindUndo(5)
    expect(() => dsu.undo()).toThrow('UnionFindUndo: nothing to undo')
    dsu.union(0, 1)
    dsu.undo()
    expect(() => dsu.undo()).toThrow('UnionFindUndo: nothing to undo')
  })

  it('throws error for rollback with invalid version', () => {
    const dsu = new UnionFindUndo(5)
    dsu.union(0, 1)
    dsu.union(2, 3)
    expect(() => dsu.rollback(-1)).toThrow(RangeError)
    expect(() => dsu.rollback(5)).toThrow(RangeError)
  })

  it('handles empty union-find', () => {
    const dsu = new UnionFindUndo(0)
    expect(dsu.componentCount).toBe(0)
    expect(dsu.size).toBe(0)
  })

  it('union by size ensures balanced trees', () => {
    const dsu = new UnionFindUndo(10)
    for (let i = 1; i < 5; i++) {
      dsu.union(0, i)
    }
    expect(dsu.getSize(0)).toBe(5)
    dsu.union(5, 6)
    dsu.union(5, 7)
    dsu.union(5, 8)
    dsu.union(5, 9)
    expect(dsu.getSize(5)).toBe(5)
    dsu.union(0, 5)
    expect(dsu.componentCount).toBe(1)
    expect(dsu.getSize(0)).toBe(10)
  })

  it('connected returns false for separate sets', () => {
    const dsu = new UnionFindUndo(3)
    expect(dsu.connected(0, 1)).toBe(false)
  })

  it('undo reverts last union', () => {
    const dsu = new UnionFindUndo(3)
    dsu.union(0, 1)
    expect(dsu.connected(0, 1)).toBe(true)
    dsu.undo()
    expect(dsu.connected(0, 1)).toBe(false)
  })
})